### ISSUE TITLE
Command-line app release?

### ISSUE THREAD

**Issue by kamilchm** [bitwalker/distillery#10]
Any easy way to release command line app like described in https://github.com/bitwalker/exrm/pull/37?

**Comment by bitwalker** [comment]
There is a path for it now yes, but probably still nothing quite like what @alco wanted initially.

Currently, you would implement your CLI commands using the `commands` setting. You can read more about it [here](https://hexdocs.pm/distillery/custom-commands.html), but here's a quick example:

```elixir
use Mix.Releases.Config

release :mycli do
  set version: current_version(:mycli)
  set commands: [
    "echo": "rel/commands/echo.sh",
    "run": "rle/commands/run.sh",
    ..snip..
  ]
end
```

```sh
# echo.sh
shift
echo "$@"

# run.sh
set -- "$BINDIR/erlexec" \
    -boot "$REL_DIR/test" \
    -boot_var ERTS_LIB_DIR "$ERTS_LIB_DIR" \
    -env ERL_LIBS "$REL_LIB_DIR" \
    -pa "$CONSOLIDATED_DIR" \
    -config "$SYS_CONFIG_PATH" \
    -mode interactive \
    -noshell \
    -eval "{S,_} = 'Elixir.Code':eval_string('Elixir.List':to_string(\"$2\")), _ = io:fwrite(\"~s\n\", [binary_to_list(S)]), init:stop()." \
    -extra ${EXTRA_OPTS}
exec "$@"
```

The `run` command just evals an Elixir code string and prints the result. Running the `run` command would look like this:

```
> bin/mycli run "inspect %{}"
%{}
>
```

However, the release package still has to be extracted in order to run these commands. But an installer could presumably install the release somewhere on the filesystem, and then symlink the release script into `/usr/local/bin` or something, so that's less of an issue I think.

I think that this is likely to be about as good as it gets as far as making an Erlang/Elixir self-contained CLI application will get. I should note too that my implementation above there boots the release package, evals/prints the string, then exits, but that startup/shutdown process adds time. Using the `nodetool` helper, with an already running release, is much faster. Executing an escript would likely be a better approach though, due to startup time.

**Comment by bitwalker** [comment]
I'm closing this for now, the command functionality provided by distillery is as far as I can take this kind of thing for now. I'm always doing more digging to see how I can improve things though, so I'll be keeping this in mind for the future.
