### ISSUE TITLE
Setting cookie

### ISSUE THREAD

**Issue by gaynetdinov** [bitwalker/distillery#129]
### Steps to reproduce

Put into `rel/config.exs` the following
```
environment :my_env do
  set include_erts: true
  set include_src: false
  set cookie: :foo
  set vm_args: "rel/vm.args/my_env"
end
```

Inside `rel/vm.args/my_env` set different cookies, like `bar`.

Deploy a release with such settings.

### Description of issue

Once deployed, a release will be using cookie name `bar` from custom `vm.args` file. Cookie name from `environment` block will be ignored. The issue is that if I remove `cookie: :foo` from `environment` block I'll get the following warning:

```
==> Attention! You did not provide a cookie for the erlang distribution protocol in rel/config.exs
    For backwards compatibility, the release name will be used as a cookie, which is potentially a security risk!
    Please generate a secure cookie and use it with `set cookie: <cookie>` in rel/config.exs.
    This will be an error in a future release.
```

So it seems like `cookie` in `environment` block should be set anyways, despite the fact that this cookie can be overridden by custom `vm.args` file. So I have to leave `cookie` param in `enviroment` block (with any value actually) just to hide this warning, because I'm using `cookie` from custom `vm.args` file which is different per environment.

**Comment by spscream** [comment]
What param do you set in vm.args? Since this warning should be fixed by this commit: https://github.com/bitwalker/distillery/commit/b15c1071e97075431ae83f5d0f9b6feac25b7e17

**Comment by gaynetdinov** [comment]
@spscream I set cookies in my custom `vm.args` file like this `-setcookie bar`

**Comment by bitwalker** [comment]
@spscream It's a warning at build-time, not runtime.

@gaynetdinov The reason why that warning exists is because we can't know (without parsing the custom vm.args file), whether you've provided your own cookie. I would suggest leaving the generated one, or just put something like `set cookie: :placeholder`, which indicates you are providing one of your own accord.

I could add a setting to silence this warning, but it's there for a reason, and I would suggest just leaving a placeholder value in rel/config.exs.
