### ISSUE TITLE
[Idea] Adapterize transport and storage of releases

### ISSUE THREAD

**Issue by schnittchen** [bitwalker/distillery#136]
This came up in #81.

Currently, releases are built on the build server, copied from there to the developer machine, then copied to a production/staging environment and unpacked.

It would be nice to be able to transport over a different channel. This would also allow people to store old releases in a shared location. I could see people to want to use s3 for this, for example.

**Comment by aphillipo** [comment]
I use this to do the AWS/S3 bit; not idea if it should be done semi automatically with some other system.

https://www.varvet.com/blog/easy-auto-scaling-elixir-deployment-with-aws-and-travis-ci/

**Comment by akurkin** [comment]
do you guys plan to expand distillery to do the "deployment" job, and not just preparing release?

Because I think in current state distillery kinda works like that:
- distillery - generating release
- something else (shell scripts, ci system, etc) - handling release delivery, i.e. store artifact, retrieve artifact, push artifact to the server, etc

What's the end vision of distillery? Being a tool for generating release or being like a swiss-army knife for building/deploying elixir apps?

If the end vision is a tool for generating release, I was wondering if it makes sense to handle storage / builds separately.

But then if the end vision is swiss-army knife, I think it makes sense to think on how to make it full-featured, expandable deployment tool, and in this case adapters for storage system is just a small piece. For example you would have adapters for storage, adapters for delivery, restart strategy. And then I think it will be useful to design how it will work overall first 🙂

**Comment by schnittchen** [comment]
There is value in having release building and deployment integrated, for example it would be possible to make connecting to a remote node more seamless. Currently, deployment knows about the nodes and release handling about cookies. See also https://github.com/schnittchen/ex_proxy_connect.

But there are probably also good reasons for keeping them separate.

Maybe here is not the best place to discuss this. There is also the edeliver repo and the #deployment slack channel...

**Comment by michalmuskala** [comment]
I think it's best to keep it separate. The problem with bundling things together is that they require more maintenance and this slows down the development of the core features. By keeping building releases and delivery of them separate we have a higher chance of getting both solved in a quality way instead of getting one big half-finished solution.

**Comment by bitwalker** [comment]
I agree with @michalmuskala, Distillery itself will never be a deployment automation tool. There are already a number of third-party tools which integrate with Distillery and handle that portion of it. The goals I have for this project are to make release generation as painless as possible, will still flexible enough to be used with whatever deployment strategy a project requires. Part of that is making Distillery extendable and configurable, so that tools like `edeliver` can plug Distillery in and focus on being really good deployment tools, instead of having to deal with the packaging aspect.

As per the OP's request though, I think this can probably already be handled today with a plugin which runs pre-release and post-packaging hooks to fetch previous releases and store generated releases respectively. Is there a reason why that model doesn't work today or is not ideal?

**Comment by schnittchen** [comment]
This is probably a very sane decision for the project.

Should somebody not be able to use hooks for this as described, he/she should open another ticket.
