### ISSUE TITLE
Issue generating tar file

### ISSUE THREAD

**Issue by cjimison** [bitwalker/distillery#208]
### Steps to reproduce

When I try to build my tar file I get an error with systools

 MIX_ENV=prod mix release --verbose --name=pg_master_app --env=prod

### Verbose Logs

==> Packaging release..
==> Archiving pg_master_app-0.15.0
==> Writing tarball to _build/prod/rel/pg_master_app/releases/0.15.0/pg_master_app.tar.gz
==> with options [:silent, {:path, ['_build/prod/rel/pg_master_app/lib/*/ebin']}, {:dirs, [:include]}, {:outdir, '_build/prod/rel/pg_master_app/releases/0.15.0'}, {:erts, '/home/cjimison/workspace/erlang'}]
==> Release packaging failed due to errors:
    {{case_clause,
     {'EXIT',
         {function_clause,
             [{filename,join,[[]],[{file,"filename.erl"},{line,395}]},
              {erl_tar,split_filename,4,[{file,"erl_tar.erl"},{line,471}]},
              {erl_tar,create_header,3,[{file,"erl_tar.erl"},{line,400}]},
              {erl_tar,add1,4,[{file,"erl_tar.erl"},{line,323}]},
              {erl_tar,foreach_while_ok,2,[{file,"erl_tar.erl"},{line,1000}]},
              {systools_make,add_to_tar,3,
                  [{file,"systools_make.erl"},{line,1903}]},
              {systools_make,add_appl,7,
                  [{file,"systools_make.erl"},{line,1774}]},
              {systools_make,'-add_applications/5-fun-0-',6,
                  [{file,"systools_make.erl"},{line,1593}]}]}}},
 [{systools_make,'-add_applications/5-fun-0-',6,
      [{file,"systools_make.erl"},{line,1593}]},
  {lists,foldl,3,[{file,"lists.erl"},{line,1263}]},
  {systools_make,add_applications,5,[{file,"systools_make.erl"},{line,1592}]},
  {systools_make,mk_tar,6,[{file,"systools_make.erl"},{line,1586}]},
  {systools_make,mk_tar,5,[{file,"systools_make.erl"},{line,1562}]},
  {systools_make,make_tar,2,[{file,"systools_make.erl"},{line,336}]},
  {'Elixir.Mix.Releases.Archiver',make_tar,1,
      [{file,"lib/mix/lib/releases/archiver.ex"},{line,68}]},
  {'Elixir.Mix.Releases.Archiver',archive,1,
      [{file,"lib/mix/lib/releases/archiver.ex"},{line,17}]}]}

### Description of issue

I added an extra log statement to print out the options too (which is why that statement is there)

I also tried moving my project into /tmp just to see if it was the 100 char limit that existed before but I am still getting the error.

Elixir 1.3.3 (installed via kiex)
Erlang: 19.1 (installed via kerl)
Distillery: Latest on master
OS: Ubuntu 16

As always any help is greatly appreciated :)

-Chris

**Comment by bitwalker** [comment]
This means you have a file name (due to module name length) which exceeds 100 characters in length. I got a PR merged into OTP to update `erl_tar` with support for PAX headers in the tarball, which effectively remove any file name limits, but that likely won't be released until OTP 20 at the earliest. Unfortunately, the only way to address this is to reduce the nesting of namespaces on your modules to keep them under this limit until the fix makes it into the next OTP release.

**Comment by cjimison** [comment]
That is going to be a bit rough for us to do.  If I wanted to create my own tar file via our build systems what files do I need to include?  Just tar everything in the /rel/<appname> then put it in the /rel/<appname>/releases/<VSN> ?

**Comment by bitwalker** [comment]
You can definitely do that if you aren't doing upgrades, if you are though, then that approach won't work since the release handler still uses `erl_tar`.

All you need to do is tar up the contents of `_build/<env>/rel/<release_name>`, that's a simplification of what Distillery does, but it will work for standalone releases no problem.

**Comment by cjimison** [comment]
As much as I would love to keep supporting upgrades I think that is the path we will have to go down until get the patch to erl_tar.  Thanks for the help!!

**Comment by bitwalker** [comment]
No problem!
