### ISSUE TITLE
Is it possible to hot reload configuration that depends on environment variables?

### ISSUE THREAD

**Issue by jesseshieh** [bitwalker/distillery#251]
Hi!

I am able to successfully hot upgrade code which I believe also upgrades my sys.config and vm.args files. I am also able to use REPLACE_OS_VARS in order to substitute environment variables into my sys.config and vm.args at boot time. 

My question is, is there a way to hot update the environment variables that get substituted into sys.config and vm.args?  

For example, if I have an app running with the following config.exs and [your awesome Config module](https://gist.github.com/bitwalker/a4f73b33aea43951fe19b242d06da7b9) installed.

```
config :myapp,
    config1: {:system, "ENV_VAR1"},
    config2: "$ENV_VAR2"
```

and myapp is booted with 

    REPLACE_OS_VARS=true ENV_VAR1=foo ENV_VAR2=bar bin/myapp start

then 

    Config.get(:myapp, :config1) == "foo"
    Config.get(:myapp, :config2) == "bar"

Is there a way to hot update the configuration without a restart so that

    Config.get(:myapp, :config1) == "newfoo"
    Config.get(:myapp, :config2) == "newbar"

?

Thanks for your help!

**Comment by michalmuskala** [comment]
That's why environment variables are not ideal for configuration - their value can only be set from the outside at the start of the program, and that's not a limitation of Elixir or Erlang, but of the operating system. From inside, you could use `System.put_env/2` - but this would work only if you read the env variable each time you use it, i.e. not with `REPLACE_OS_VARS`.

Regular application config can be changed with `Application.put_env/3` or during the release upgrade.

**Comment by jesseshieh** [comment]
Thanks for the quick reply @michalmuskala! 

If I call `System.put_env/2` and then do a hot upgrade, and then call `Config.get/2` will I get the new value or the old one? 

Also, is there a way to do the same thing, but without a hot upgrade? Perhaps by calling `System.put_env/2` and then calling `reload_config`? By skimming the source code, it doesn't look like `reload_config` replaces OS vars.

**Comment by bitwalker** [comment]
If you set the environment variable externally, then do a hot upgrade, the new value will be used. As @michalmuskala mentioned, if you use `System.put_env/2` to change them, then you need to use `System.get_env/1` in order to see those changes, they won't be used in updating the configuration during a hot upgrade.

Using `reload_config` is the same, you need to set environment variables outside of the app, so that the config loader can see those changes, but this will update configuration without a hot upgrade, and it does do environment variable replacement. The key thing here is that if you are using libaries/apps which configure themselves once upon application startup, then configuration changes won't take place without a hot upgrade/restart. The other thing to be aware of is that if configuration for a socket connection changes, the socket will not, unless you do a hot upgrade and the library handles disconnecting/reconnecting in it's `code_change` handler, or you restart the connection process.

**Comment by jesseshieh** [comment]
Thanks @bitwalker! Very helpful!
