### ISSUE TITLE
Race condition and other strange behaviour when bin script interacts with node

### ISSUE THREAD

**Issue by schnittchen** [bitwalker/distillery#262]
I'm writing some tooling around distillery and simply can't wrap my head around what is going on here. I was able to reduce the problem down to the interaction below, which demonstrates several issues. I am posting this here because the `bin/dummy1` script is generated by distillery IIRC.

There are five runs of the same list of shell commands (each on a long line). Runs 2 and 5 show an additional error. 

```
user@ubuntu-xenial:~/dummy1_app_path$ bin/dummy1 start; for i in {1..10}; do bin/dummy1 ping && break || true; sleep 1; done; bin/dummy1 stop
pong
ok
user@ubuntu-xenial:~/dummy1_app_path$ bin/dummy1 start; for i in {1..10}; do bin/dummy1 ping && break || true; sleep 1; done; bin/dummy1 stop
vm.args needs to have either -name or -sname parameter.
pong
ok
user@ubuntu-xenial:~/dummy1_app_path$ bin/dummy1 start; for i in {1..10}; do bin/dummy1 ping && break || true; sleep 1; done; bin/dummy1 stop
Node 'dummy1@127.0.0.1' not responding to pings.
pong
ok
user@ubuntu-xenial:~/dummy1_app_path$ bin/dummy1 start; for i in {1..10}; do bin/dummy1 ping && break || true; sleep 1; done; bin/dummy1 stop
Node 'dummy1@127.0.0.1' not responding to pings.
Node 'dummy1@127.0.0.1' not responding to pings.
Node 'dummy1@127.0.0.1' not responding to pings.
Node 'dummy1@127.0.0.1' not responding to pings.
Node 'dummy1@127.0.0.1' not responding to pings.
Node 'dummy1@127.0.0.1' not responding to pings.
Node 'dummy1@127.0.0.1' not responding to pings.
Node 'dummy1@127.0.0.1' not responding to pings.
Node 'dummy1@127.0.0.1' not responding to pings.
Node 'dummy1@127.0.0.1' not responding to pings.
user@ubuntu-xenial:~/dummy1_app_path$ bin/dummy1 ping
pong
user@ubuntu-xenial:~/dummy1_app_path$ bin/dummy1 start; for i in {1..10}; do bin/dummy1 ping && break || true; sleep 1; done; bin/dummy1 stop
escript: exception error: no function clause matching erlang:set_cookie(nonode@nohost,
                                                               'IPa5OGx-=s}A&;Om&T]c>9dWU3d*hIBPtD9wKl_%%(I;[Q80tEx7/$O+gyk`cXb^\nIPa5OGx-=s}A&;Om&T]c>9dWU3d*hIBPtD9wKl_%%(I;[Q80tEx7/$O+gyk`cXb^') 
pong
ok
```

Can you help me figure this out?

**Comment by schnittchen** [comment]
When the 10x "Node not responding" thing happens, I usually (not always) find this in erlang.log.1:

```
could not start kernel pid (application_controller) (error in config file "/home/user/dummy1_app_path/var/sys.config" (none): configuration file must contain ONE list ended by <dot>)
```

**Comment by bitwalker** [comment]
Is this occurring in master or a specific version? I'll take a look tonight or tomorrow as soon as I get a chance.

The boot script is actually called recursively when starting the daemon, I thought we had worked the kinks out, but I suspect what is happening is that the first point is happening right when `run_erl` is invoking the script to start the application, and depending on how the release is set up, `sys.config` and `vm.args` are both written to the mutable directory, so there is a race condition possible there if the ping is in the middle of rewriting one or the other when the VM boots.

There is plenty that could be done to eliminate the race, but since you're the first one to break it ;), I haven't had a good example of how to reproduce it. Should be pretty easy to fix it when I take a look.

**Comment by schnittchen** [comment]
Oh my. Somehow I'm way behind, "~> 0.9" resulting miraculously in `{:hex, :distillery, "0.10.1", "14fccade...`.

I will look into that tomorrow. I wonder where I picked up the ancient dep spec...

**Comment by schnittchen** [comment]
I'm up-to-date now and the problem seems gone. Thank you.

**Comment by bitwalker** [comment]
Glad to hear it! Thanks for following up :)
