### ISSUE TITLE
Phoenix 1.3 static files not hot upgraded 

### ISSUE THREAD

**Issue by illyas3** [bitwalker/distillery#270]
### Steps to reproduce

- Build a project with Phoenix 1.3.0-rc 
- Make a release (version 0.0.1) with `MIX_ENV=prod mix release --env=prod` and push it to prod 
- `./bin/app start` release starts and works correctly
- Make new release and push to production (version 0.0.2)
- `./bin/app upgrade 0.0.2` results in: 
`Release 0.0.2 not found, attempting to unpack releases/0.0.2/app.tar.gz
 Unpacked successfully: "0.0.2"
 Release 0.0.2 is already unpacked, now installing.
 Installed Release: 0.0.2
 Made release permanent: "0.0.2"`

Final result: server is being upgraded to 0.0.2 successfully, however static files (app.js) are still running from version 0.0.1. 

### Description of issue

- Expected results: have all static files upgraded with new version (0.0.2) and be served
- Possible reason for this: In Phoenix 1.3 `cache_static_manifest: "priv/static/manifest.json"` was [replaced](https://gist.github.com/chrismccord/71ab10d433c98b714b75c886eff17357) by `cache_static_manifest: "priv/static/cache_manifest.json"` in the `config/prod.exs`.

### Temporary stable solution

Run `./bin/app upgrade 0.0.2` and then `./bin/app restart` will restart the server breaking hot upgrade, but will pick up new static files once starts. 

### Temporary buggy solution

Change back `cache_static_manifest: "priv/static/manifest.json"` in `config/prod.exs` like on previous phoenix versions. This results in following error, while running `./bin/app foreground`:
`[error] Could not find static manifest at "/home/user/app/lib/app-0.0.2/priv/static/manifest.json". Run "mix phoenix.digest" after building your static files or remove the configuration from "config/prod.exs".`
However, `./bin/app start` and then `./bin/app upgrade/downgrade 0.0.X` works for couple updates, before it breaks and returns `Node is not running!` error. If this happens, you have to manually kill service by PID and then `./bin/app start` again. 

### The setup
```
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: Mix.env()


environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"..."
end

environment :prod do
  set plugins: [App.PhoenixDigestTask]
  set include_erts: true
  set include_src: false
  set cookie: :"..."
end

release :app do
  set version: current_version(:app)
  set applications: [
    :runtime_tools
  ]
end
```

where App.PhoenixDigestTask is 
```
defmodule App.PhoenixDigestTask do
  use Mix.Releases.Plugin

  def before_assembly(%Release{} = _release) do
    info "before assembly!"
    case System.cmd("npm", ["run", "deploy"], cd: "assets") do
      {output, 0} ->
        info output
        Mix.Task.run("phx.digest")
        nil
      {output, error_code} ->
        {:error, output, error_code}
    end
  end
end
```

### Question
Is it possible to update distillery to support new `cache_manifest.json` file, so then all the static assets will be served properly when hot upgrading/downgrading different versions in production? 

Also, checking `lib/app-0.0.2/priv/static/js/` in the production env, I can see both new and old digested js files, however it still uses the old one if hot upgrading.

**Comment by bitwalker** [comment]
It seems to me that it's probably the fact that the cache manifest location changed, but we'll need to confirm that. It looks to me like you got the "missing" error because you didn't run `mix phoenix.digest` after changing the location in the config.

I can't see any reason this doesn't work out of the box otherwise - Distillery doesn't get in the way of how individual applications handle hot upgrades, it just makes sure that they are upgraded - so it's possible this is an issue on the Phoenix side as well.

I'll try and do some testing and get back to you ASAP.

**Comment by bitwalker** [comment]
So after setting up a test project and doing some poking around, it looks to me like the change in `:cache_static_manifest` is not handled internally by Phoenix - in other words, when the `Phoenix.Config` process is updated, it is not implementing the `code_change` callback and updating/restarting the parts of the application which need to change. There isn't a good way to work around this, other than adding your own appup instructions to handle this.

In addition, with some of the recommendations documented in the 1.3 upgrade guide, there will be other issues as well with hot upgrades - the one I hit most prominently is the rename of `MyApp.Endpoint` to `MyApp.Web.Endpoint`, as that module name is referenced in Cowboy's dispatch configuration, and will result in all HTTP calls failing after upgrade.

Not sure what the best path forward is here, but I'm not sure I can do much on Distillery's end.

/cc @chrismccord

**Comment by chrismccord** [comment]
Thanks for looping me in Paul. I'm fine if users hopping on 1.3 and renaming their endpoint module need to perform a cold deploy or custom appup if they really need on. On the static manifest side, I need to double check with José since I forget our reasoning around removing code_change from new apps.

**Comment by bitwalker** [comment]
@chrismccord Yeah I think that makes sense, if there's a path for those who want to pursue hot upgrades, I think that's the important part, even if it involves additional effort, it seems like the removal of the `code_change` callback specified in the upgrade instructions might need a caveat next to it? I haven't dug deep enough to determine if that's related to the issue here though, I did notice that the Phoenix-internal module `Phoenix.Config` is missing a code change handler, but that might be intentional.

**Comment by illyas3** [comment]
Hey @bitwalker Thank you for researching this issue. I guess I'll stick with cold upgrades behind the balancer for now. 
But interested to hear why `code_change` was removed. Definitely hot upgrades are desirable, even if will require more effort.

**Comment by jespr** [comment]
@chrismccord I currently don't have the luxury of a balancer, so are there any updates on this? :) Will hot upgrades be possible when running Phoenix 1.3?

**Comment by lessless** [comment]
@chrismccord @bitwalker I know that you guys are pretty busy but since you are working closer together now maybe there are any updates on the issue that wasn't published here? 

Or nobody uses hot upgrades anymore? :)

**Comment by chrismccord** [comment]
@lessless We added code_change back to the endpoint before 1.3 went final. Are we sure this is still an issue for folks?

**Comment by lessless** [comment]
That's what I would love to know as well since we already scheduled upgrade to 1.3

**Comment by bitwalker** [comment]
@chrismccord I forgot to chime back in here, but yes, the `config_change` callback is key, so that the static asset path can be updated (the config in the application env will be updated regardless, but IIRC, Phoenix stores that config on startup somewhere, and it was only being re-persisted when `config_change` was called during upgrades. There are probably some other things you could do within `config_change` to make hot upgrades pretty seamless, but for sure getting any paths propagated is really important.
