### ISSUE TITLE
RFC: Allow archival of release when dev_mode is enabled

### ISSUE THREAD

**Issue by IljaN** [bitwalker/distillery#283]
Hi,

to simplify deployment to different environments via Docker it would be helpful if archive creation could be enabled separately for dev environment without turning dev_mode off.

This is my line in Dockerfile:
```yaml
COPY _build/${MIX_ENV}/rel/${APP_NAME}/releases/${VERSION}/${APP_NAME}.tar.gz /app/${APP_NAME}.tar.gz
```

As of now I would need a different command to deploy with dev-mode (no tar.gz).
Should I try to do a PR?

**Comment by bitwalker** [comment]
It is intentional that `dev_mode` disables archival - `dev_mode` is intended for quick iteration during development with releases, i.e. everything is symlinked to the release directory, to drastically speed up the execution of `mix release` - archival defeats the purpose of that. It sounds like what you need instead is to modify your `:dev` environment configuration in `rel/config.exs`, changing `dev_mode: true` to `dev_mode: false`.

It looks like we're still accidentally asking `:systools` to generate a tarball though when `dev_mode` is enabled, which shouldn't be the case (it doesn't include everything the normal tarball contains, so it's not the same thing).

If the above isn't the answer to your question, could you clarify what you're looking to accomplish? It's not clear to me why you want `dev_mode` to be enabled if you want a tarball generated.

**Comment by bitwalker** [comment]
ping :)

**Comment by IljaN** [comment]
I assumed that dev_mode maybe also compiles things differently , if this is not the case then my question is solved.

**Comment by bitwalker** [comment]
Yeah, no it compiles things the exact same, it simply symlinks the files in to the release directory so the release/code/test cycle is much faster.
