### ISSUE TITLE
Passing arguments to rpc functions

### ISSUE THREAD

**Issue by ftaebi** [bitwalker/distillery#29]
bitwalker, how are function arguments supposed to be passed to rpc.
Using exrm i can do 

```
rel/myapp/bin/myapp rpc Elixir.Application get_all_env 'myapp.'
```

or

```
rel/analysis_backend/bin/analysis_backend rpc calendar day_of_the_week "[2016,08,13]."
```

and it works as expected. But it seems like this is not the correct way with distillery releases..

I couldn't find any tests or examples.

**Comment by bitwalker** [comment]
It looks like the handling of arguments isn't great in some cases. You don't need the trailing `.` though, that might be messing with it. I still need to wrap these things in tests.

In general I would recommend the use of `eval` instead, it's a more natural way of expressing the calls. To use your examples:

```
rel/myapp/bin/myapp eval "'Elixir.Application':get_all_env(my_app)"

rel/analysis_backend/bin/analysis_backend eval 'calendar:day_of_the_week({2016,8,13})'
```

**Comment by Faolain** [comment]
Hey all I'm not sure if this is related but I figured I would ask anyway. I'm currently trying to run an rpc task to migrate my database after initializing my application, however I'm attempting to do so after changing the name of my node in my vm.args(as I'm deploying a container packaged with the distillery binary through rancher - an orchestration tool). 

```
## Name of the node - this is the only change
-name hello@${RANCHER_IP}
```

However once the name of the node is different... and I try to run 
```
bin/hello rpc Elixir.Release.Tasks migrate
```

I get
```
4/23/2017 3:22:24 PM RPC to 'hello@10.42.65.9' failed: nodedown
```

I was wondering if this is due to the fact that rpc requires the host to be `@127.0.0.1` instead of the new host ip? If so is there a way to migrate a database in distillery without resorting to an RPC call(since Mix is not available)? Or barring that is it possible to point toward a particular host in the RPC call other than `127.0.0.1`?

Here is the attached comment in another repo along with a gist of all the files involved:
https://github.com/Recruitee/mix_docker/issues/25#issuecomment-296484153

**Comment by DylanReile** [comment]
@Faolain I also experience the ERL crash when using the Distillery custom command and the "Node is not running!" error when using RPC. Did you ever find a resolution?

**Comment by bitwalker** [comment]
The new tooling in master now provides `rpc` for remote and `eval` for local which both take an arbitrary Elixir expression and evaluate it (the location where it is evaluated is based on the command):

```
$ bin/myapp rpc "Release.Tasks.migrate"

or

$ bin/myapp eval "Enum.each(["foo", "bar], &IO.puts/1)"
foo
bar
```
