### ISSUE TITLE
If TERM is set to dumb, input to remote shell is handled incorrectly

### ISSUE THREAD

**Issue by ananthakumaran** [bitwalker/distillery#298]
```
[root@http-worker-2 bin]# ./worker remote_console
==> Generated sys.config in /app/var
Interactive Elixir (1.4.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(remsh6a934a8d-worker@127.0.0.1)1> :inet.i
Port  Module   Recv Sent Owner    Local Address   Foreign Address State     Type
32800 inet_tcp 0    0    <0.49.0> *:39581         *:*             ACCEPTING STREAM
33312 inet_tcp 4    35   <0.47.0> localhost:58169 localhost:epmd  ????      STREAM
:ok
iex(remsh6a934a8d-worker@127.0.0.1)2> ^C
```

when the TERM is dumb(docker/kubectl exec by default loads a dumb terminal [1](https://github.com/moby/moby/issues/8631)), the remote_console seems to work, but all the commands get executed in the local shell. We figured out the issue after a bit of head-scratching. Perhaps a warning could be added if the shell is dumb?. Feel free to close this issue if you think it is unnecessary.

**Comment by bitwalker** [comment]
What version are you using? The boot script sets `TERM=xterm` if `TERM` is not already set, and exports it to the rest of the script - specifically to handle this issue. I did that because I ran into this with Docker/k8s as well, but in my base Docker images I also set `TERM=xterm`, so perhaps something isn't being picked up but I haven't noticed it because of that. It was a post-1.0 thing though, so it may not be present depending on what version you are on.

**Comment by ananthakumaran** [comment]
I am on version 1.4.1. I could find the following chunk in the shell file.

```sh
# If TERM is not set, set it to xterm
if [ -z "$TERM" ]; then
    export TERM=xterm
fi
```

```sh
[root@http-worker-2 app]# echo $TERM
dumb
```

But the TERM is set to `dumb` in my case.

**Comment by bitwalker** [comment]
Oh interesting, I will tweak that code to check for that as well. In the meantime, setting TERM=xterm in the environment of the app should work around it for now
