### ISSUE TITLE
Can not pass arguments via `command module fun [args..]`

### ISSUE THREAD

**Issue by AndrewDryga** [bitwalker/distillery#305]
I'm trying to pass an argument to the function in a release task and it doesn't seem to work:
```
myapp command "Elixir.MyReleaseTasks" migrate "Hi" 123
{"init terminating in do_boot",{undef,[{'Elixir.MyReleaseTasks',migrate,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{Elixir.MyReleaseTasks,migrate,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})
```

As you can see in error produced by VM, Distillery is trying to call `migrate/0` without arguments, which is undefined.

**Comment by bitwalker** [comment]
Is this with master or a specific tag?

**Comment by AndrewDryga** [comment]
Latest version from hex.pm.

**Comment by bitwalker** [comment]
Oh wait, sorry - just remembered that `command` does not take arguments which are passed to the function call. You can access command line arguments with `:init.get_plain_arguments` though.

The problem is that we don't have a good way of handling the arguments to the function itself, specifically the issue of types - we basically could only support binaries as arguments, which doesn't make it very useful. We could provide an `eval`-like task which works like eval but doesn't require RPC to a live node - but that doesn't exist right now. It can be implemented fairly easily via custom commands if needed.

I am open to suggestions from the community on what people want to see here though - if there is an overwhelming desire to see command work this way, we can probably change the way it works as a breaking change, but I'd prefer to do a deprecation cycle by introducing a new command, then eventually aliasing `command` to it, then deprecating `command` (I don't like that name much anyway).

**Comment by michalmuskala** [comment]
What if we didn't invoke the function directly? What if we invoked something first that would parse the arguments and only then call the function? Something like:

```erlang
erlang:apply(Module, Function, init:get_plain_args())
```

We could sprinkle some `:erl_parse` to support all the types, but I guess even only strings would be better than nothing we have right now

**Comment by bitwalker** [comment]
@michalmuskala That is a possibility, but rather than looking at the Erlang/Elixir side first, I think it's worth working through how we want to be able to invoke an MFA from the command line, and walk through how to make it work, or at least determine from there what the limitations are. For example, here are some options:

1.) `bin/myapp command "Module" "fun" "[foo, \"bar\", 42]"`
2.) `bin/myapp command "Module" "fun" "foo" "\"bar\"" "42"
3.) `bin/myapp command "Module.fun(foo, \"bar\", 42)"

1 takes an expression to parse into an Erlang term, which will then be passed to the function via `apply`. 2 parses each of the arguments after the module/function into individual terms, and the function is invoked again via `apply`. 3 simply evals an expression.

There are perhaps other variations which are more comfortable, these are just the 3 I came up with in the last 30 seconds. Once we land on an invocation style, I think working out an implementation will be pretty straightforward.

The other thing I think would be good to consider as part of this is switching from Erlang syntax to Elixir syntax - it's possible, I just haven't done so yet.

**Comment by bitwalker** [comment]
Also, if anyone has suggestions for a name, I'm all ears - I'd like to get away from `command` which isn't very descriptive. I'm leaning towards `apply` since it's more or less what we're doing with it.

**Comment by vasspilka** [comment]
I like option 1 best, `command` is ok I guess, apply could confuse.

**Comment by bitwalker** [comment]
In master, local eval is supported with, for example, `bin/myapp eval "Enum.map(["foo", "bar], &IO.puts/1)"`, remote eval is the same, but via `rpc`. Old form of `rpc` and `rpcterms` commands are removed, and `eval` is no local rather than remote.

**Comment by jesseshieh** [comment]
@bitwalker first off, thanks for all your awesome work. Quick question for you: one of the things I liked about `command` over `eval` was that it didn't require a running node. Since it looks like `command` isn't going to handle arguments, do you have a suggestion for the best way to call a function with arguments without a running node? 

In other words, when I run
```
$ bin/app command Elixir.Tasks migrate 1 2
Tasks.migrate is either not defined or has a non-zero arity
```
and when I run
```
$ bin/app eval "Tasks.migrate(1, 2)"
Node app@127.0.0.1 is not running!
```

I don't necessarily want to call `foreground &` before calling `eval` because it might spin up duplicate processes that are running on the "real" app server that is serving traffic.

**Comment by bitwalker** [comment]
@jesseshieh That's a bug :) - `eval` shouldn't require a running node, I'll make sure that gets addressed in master

**Comment by bitwalker** [comment]
@jesseshieh I just tested on my machine and I'm not able to replicate this, are you using `master` or `1.5.x`?

**Comment by jesseshieh** [comment]
@bitwalker Thanks for the speedy reply! Looks like I'm on 1.5.2. I'll try it on master.
```
$ cat mix.lock | grep distillery
  "distillery": {:hex, :distillery, "1.5.2", "eec18b2d37b55b0bcb670cf2bcf64228ed38ce8b046bb30a9b636a6f5a4c0080", [], [], "hexpm"},
```

**Comment by jesseshieh** [comment]
@bitwalker works perfect on master. I also tested 1.5.3 which had the same bug.

**Comment by bitwalker** [comment]
It actually is expected in 1.5.3 - the semantics have changed in 2.x (i.e. master). Previously, `rpc`, `rpcterms`, and `eval` where all slightly different ways of executing code on a remote node. In 2.x, `rpc` is for remote execution, and `eval` is for local execution, and they both share the same API (i.e. passing a string of code to evaluate, or `--file <path>` to a script to evaluate). The idea being to simplify the API and get rid of the redundant commands and confusing syntax.

**Comment by jesseshieh** [comment]
@bitwalker ah got it! Can't wait for 2.x :) and also can't wait till mix uses releases!

**Comment by IanVaughan** [comment]
Using v2.0.9 I get the "the process is not alive" error.

```bash
$ cat mix.lock | grep distillery
"distillery": {:hex, :distillery, "2.0.9", "1e03e1bd97c0cd1187ce5882143fcc44812aa54d8c61b093801fab053bf07c98", [:mix], [{:artificery, "~> 0.2", [hex: :artificery, repo: "hexpm", optional: false]}], "hexpm"},

=$ _build/prod/rel/myapp/bin/myapp eval "Enum.each(["foo", "bar"], &IO.puts/1)"
** (exit) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) gen.erl:261: :gen.do_for_proc/2
    (stdlib) gen_event.erl:197: :gen_event.rpc/2
    (artificery) lib/console.ex:270: Artificery.Console.init/0
    (distillery) lib/entry.ex:42: Mix.Releases.Runtime.Control.main/1
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/code.ex:192: Code.eval_string/3
```
Not sure if I've got some config/setup incorrect?
