### ISSUE TITLE
After upgrade on 1.5.0 release isn't starting on alpine:3.5 docker image

### ISSUE THREAD

**Issue by spscream** [bitwalker/distillery#308]
I upgraded distillery to 1.5.0, build new release and docker image with it, based on this Dockerfile:
```
FROM alpine:3.5

RUN apk add ncurses --update-cache --repository http://nl.alpinelinux.org/alpine/edge/main && \
    rm -rf /var/cache/apk/*

ENV APP_NAME phonebook
ENV PORT 4000

ADD $APP_NAME.tar.gz /app/
WORKDIR /app

EXPOSE $PORT

CMD trap exit TERM; /app/bin/$APP_NAME foreground & wait
```

On image start I got this:
```
/app # ./bin/phonebook start
/bin/sh: ./bin/phonebook: not found
/app # sh -x ./bin/phonebook start
<....skipped...>
+ BINDIR=/app/erts-8.2.2/bin
+ export ERTS_LIB_DIR
+ ERTS_LIB_DIR=/app/erts-8.2.2/../lib
+ export EMU=beam
+ export PROGNAME=erl
+ otp_vsn
+ erl -eval Ver = erlang:system_info(otp_release), io:format("~s~n", [Ver]), halt() -noshell -boot start_clean
+ whereis_erts_bin
+ [ -z 8.2.2 ]
+ __erts_dir=/app/erts-8.2.2
+ [ -d /app/erts-8.2.2 ]
+ echo /app/erts-8.2.2/bin
+ __erl=/app/erts-8.2.2/bin/erl
+ [ -z /app/erts-8.2.2/bin/erl ]
+ /app/erts-8.2.2/bin/erl -eval Ver = erlang:system_info(otp_release), io:format("~s~n", [Ver]), halt() -noshell -boot start_clean
+ OTP_VER=19
+ export OTP_VER
+ __pid=
+ [ 19 -ge 20 ]
+ exec /app/releases/1.0.0/phonebook.sh start
./bin/phonebook: exec: line 1: /app/releases/1.0.0/phonebook.sh: not found
```

I expected release running.

**Comment by spscream** [comment]
added bash to image, it is working... Why you decide move to bash?

**Comment by bitwalker** [comment]
Was just about to post that haha

It turns out that the old boot script had an implicit dependency on a bashism (sourcing scripts with arguments) in order to handle custom commands in such a way that the environment had all of the helper functions provided as part of Distillery's API. With the refactor of the boot script to modularize it, this same behaviour was needed for Distillery's own internal scripts. I decided to make this dependency explicit rather than implicit, as I could not come up with a satisfactory way of achieving the desired behaviour while remaining compatible with POSIX `sh` and most annoyingly, Ubuntu's `dash`, which explicitly does not permit sourcing scripts with arguments. Since most platforms alias `sh` to `bash`, I only caught this when testing on different OSs myself.

I'm not happy about needing to require `bash`, but since it was already implicitly a requirement for the custom commands feature, I decided to embrace it. This issue though has made it clear that I need the boot loader script to use `sh` so that I can print an error if `bash` is not available.

**Comment by spscream** [comment]
Ok, thanks for explanation. Indeed explicit is better than implicit.

**Comment by smoak** [comment]
So does this mean that bash is required to run a release created from distillery?

**Comment by smoak** [comment]
Ah I see from the CHANGELOG.md that it is:

>IMPORTANT: Distillery now requires that Bash be installed on the target system.

That's disappointing. We use alpine for our base image which doesn't include bash. Adding bash to the image isn't possible due to security concerns. This means I won't be able to use distillery 😞

**Comment by bitwalker** [comment]
@smoak Bash isn't allowed but `sh` is? Can you explain? My alpine docker images all have bash installed, and I'm not aware of any overt security issues.

**Comment by smoak** [comment]
I'll run it by my org's security team. As far as I am aware they want to reduce the attack area so they want to strip everything down.

**Comment by bitwalker** [comment]
@smoak Makes perfect sense to reduce attack area - I'm just curious why they would feel that `sh` is less vulnerable than `bash` for my own edification. That said, the move to an explicit requirement on `bash` was motivated less out of my desire to use `bash`, and more because the shell script was using bashisms (unintentionally - I've always maintained that I wanted to stick to POSIX `sh`) that were causing problems when the scripts were run under `/bin/sh` which was an alias for another shell without support for those bashisms, namely `dash`, but it's true for others as well. I'd be glad to stick to POSIX `sh`, but I need to have solutions to the problems driving us to `bash` today, namely the ability to source or execute scripts with arguments, such that the public shell functions and environment that Distillery provides are available to those scripts. This applies primarily to custom hooks and commands. I'm not aware of an easy way to get there, but I'm open to suggestions.

**Comment by smoak** [comment]
It turns out I was mistaken and they don't really care, so I'll just add bash to our elixir image 😃

**Comment by bitwalker** [comment]
Well that's a relief :). I'm still going to keep my eyes open for ways to roll back to POSIX `sh`, but until that happens (and if it happens) it's good to know that nobody is being left behind.
