### ISSUE TITLE
Setting REPLACE_OS_VARS=true in boot hook scripts doesn't work

### ISSUE THREAD

**Issue by mconigliaro** [bitwalker/distillery#309]
In order to eliminate confusion and make troubleshooting easier in production environments, our app loads its runtime configuration environment variables via a pre_start boot hook:

```
# Load environment variables
conf=/etc/default/<app>
if [ -f "$conf" ]; then
  echo "Loading environment variables from $conf"
  . "$conf"
fi
```

The idea is to ensure that the environment variables get loaded no matter how the app is started (e.g. `./bin/<app> start`, `systemctl <app> start`, etc.). Since `REPLACE_OS_VARS=true` needs to be set for this to work, I tried setting it at the top of the boot hook script, but it doesn't seem to work there. I also tried setting it in an (undocumented?) pre_config hook, but that didn't work either. In order to work around this, I've added a line to the systemd unit file (`Environment=REPLACE_OS_VARS=true`) and another in the app user's `.profile` (`export REPLACE_OS_VARS=true`), but it would be cool if I didn't have to do this. Is there some other place I can set `REPLACE_OS_VARS=true` so that it works for all the different ways the app can be started?

**Comment by bitwalker** [comment]
This is because that hook is executed after the replacement would be done. You will need to use the `pre_configure` hook (and use Distillery 1.5+) in order to ensure that replacement occurs.

Feel free to reopen this if that doesn't work. If you are not yet on 1.5+, you'll need to export the environment variables prior to boot (whether that's via the unit file or some other mechanism).

**Comment by mconigliaro** [comment]
Ah, I didn't realize 1.5.0 was just released with a fix for this. Looks like everything working perfectly now. Thanks!
