### ISSUE TITLE
RemainAfterExit recommendation in Systemd docs

### ISSUE THREAD

**Issue by brucepom** [bitwalker/distillery#310]
In the [systemd example](https://github.com/bitwalker/distillery/blob/master/docs/Use%20With%20systemd.md) in the docs. There is a recommendation:
 

> It's important that you have RemainAfterExit=yes set, or you will get an error trying to start the service.

My experience using this example on Ubuntu was that I didn't run into any problems when omitting `RemainAfterExit=yes` from the unit file. And that including it prevented systemd from restarting the app if it crashed. I wonder if this should be the recommendation. Perhaps we include a note saying that "if you run into issues starting the service you might try adding `RemainAfterExit=yes` to your unit file. Keep in mind that adding this will prevent systemd restarting your app if it crashes. If you think this makes sense I'm happy to submit a PR. Thanks!

**Comment by bitwalker** [comment]
I wasn't the author of the systemd docs unfortunately, so I haven't verified that the instructions are necessarily correct, especially since some people run `foreground`, others use the daemon via `start`. I have some changes planned in Distillery which should make integration with systemd easier though, namely the creation of a pid file which can be given to systemd, which should be much more reliable than hoping the pid detection is picking up the right pid. Basically, one would then use `Type=forking`, `GuessMainPID=false`, and `PIDFile=<deploy_root/var/myapp.pid` in addition to any other configuration in the unit file.

If you would like to provide a PR which revamps this documentation (assuming you've followed the instructions from beginning to end yourself with success), that would be awesome! It may be worth figuring out what the unit file should be for both `foreground` and `start` use cases, since I believe they need to be different, since `start` starts a daemon and returns, whereas `foreground` is much easier (IIRC, `GuessMainPID` does the right thing there).

**Comment by OvermindDL1** [comment]
I think he created this because of my thread at:  https://elixirforum.com/t/pidfile/7620/2
So you may want to see it for details and how to properly set up the BEAM VM to work with systemd so it will actually restart properly.  :-)

And no, in my experience `GuessMainPID` often fails when using the BEAM VM (at least on my systems).

> I have some changes planned in Distillery which should make integration with systemd easier though, namely the creation of a pid file which can be given to systemd, which should be much more reliable than hoping the pid detection is picking up the right pid.

Awesome, that'd make my PIDFile library obsolete then.  It's whole purpose is just to manage a PID file for a BEAM VM.  :-)

**Comment by bitwalker** [comment]
> So you may want to see it for details and how to properly set up the BEAM VM to work with systemd so it will actually restart properly. :-)

I saw that! Very helpful :)

> Awesome, that'd make my PIDFile library obsolete then. It's whole purpose is just to manage a PID file for a BEAM VM. :-)

I kinda feel bad that I'd be making your work obsolete, but if you're like me, it's probably something you'd prefer to not have to maintain anyway haha

> Just make sure the PID is of the forked BEAM PID and not the original processes that then dies post-fork.

Yeah, I think this is why `GuessMainPID` is broken, I haven't yet looked in to the exact mechanism I plan to use for creating the pidfile, there is a relatively easy path where we just ask the running VM what it's pid is, but I'd like to be able to get it without having to wait for the VM to start responding to RPC calls.

**Comment by OvermindDL1** [comment]
> I kinda feel bad that I'd be making your work obsolete, but if you're like me, it's probably something you'd prefer to not have to maintain anyway haha

*Precisely* that! I do *not* want to maintain anything that I don't have to.  ^.^
Plus if you look it it, it is pretty dead-simple.  ^.^

> Yeah, I think this is why GuessMainPID is broken, I haven't yet looked in to the exact mechanism I plan to use for creating the pidfile, there is a relatively easy path where we just ask the running VM what it's pid is, but I'd like to be able to get it without having to wait for the VM to start responding to RPC calls.

Yeah I initially had a design that did an RPC call to get it, waiting for the server to come up, that is when I made my PIDFile library a while back so it could do it quicker than I could, and more reliably (since I was basically just polling for if it was up or not, and this made it drop-in easy).

**Comment by bitwalker** [comment]
After thinking about it for a few, what I'm probably going to end up doing is dropping an instruction in the boot script right after all the code is loaded which calls `:os.getpid()` and writes it to the file path I feed it. It's cheating since I'm able to do that, but nobody else can (unless they write their own boot script), but the upside is that it is guaranteed to happen as early as possible, will prevent the VM from booting if the pid file fails to be written, and doesn't require any applications to be started (so we don't have to wait for RPC).

**Comment by michalmuskala** [comment]
I wonder if maybe a contribution upstream to OTP that adds a `-pidfile path/to/file` VM argument could be accepted.

**Comment by bitwalker** [comment]
I suspect it probably would be, and I think that should probably be the ultimate goal.
