### ISSUE TITLE
Does the release name matter?

### ISSUE THREAD

**Issue by jesseshieh** [bitwalker/distillery#337]
Hi! I ran into an interesting issue today and was wondering if I'm doing something wrong.

My application is called `:server` i.e. in `mix.exs` it says `app: :server`

When I set my `rel/config.exs` release name to `:server` all works fine i.e.
```
release :server do
...
```

If I change it to something else, though, Distillery complains about missing `:applications` e.g.
```
release :foo do
...
```

Errors I get look like this
```
$ MIX_ENV=prod mix release --env=prod
==> Assembling release..
==> Building release foo:0.0.1 using environment prod
==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :phoenix
    :phoenix_ecto
    :postgrex
...
```

Is this expected behavior or could I be doing something wrong? I'm using Distillery 1.5.2 and Phoenix 1.3.0.

Thanks!!

**Comment by jesseshieh** [comment]
Ah, I was also able to fix the issue by adding `:server` to the release applications. e.g.
```
release :foo do
  set applications: [
    :server
  ]
...
```

**Comment by bitwalker** [comment]
Yeah this is covered somewhat in the documentation, though primarily in the context of umbrella apps because that's where this almost universally comes up (otherwise there is very little reason to change the default config). If the release name doesn't match the application name, or the release is for an umbrella, you have to specify the top-level applications which will be included in the release by their name, which tells Distillery how to determine what needs to be in the release. We can't just infer that a release of any name refers to the current project, since it could be an umbrella, and it isn't always desirable to include all of the applications in the umbrella in a single release. We could do that just for non-umbrella projects, but since that effectively is the default behaviour already (since the generated config has a release named the same as your app), there hasn't been much of an incentive to change that. Hope that helps!

**Comment by jesseshieh** [comment]
Very helpful as usual! Thank you!
