### ISSUE TITLE
skip compiling when run mix release

### ISSUE THREAD

**Issue by xdays** [bitwalker/distillery#358]
### Steps to reproduce

```
mix do deps.get, deps.compile, compile
mix test
mix release
```

### Verbose Logs

Paste the output of the release command you ran with the `--verbose` flag.

### Description of issue

We have a ci pipeline including running unit tests and packaging with distillery, and both of them compile source code, so our ci time doubles. Is there anyway can we skip compiling when running `mix release`?

**Comment by bitwalker** [comment]
Given your snippet, it is no surprise compilation is performed twice, `mix test` needs to compile for `MIX_ENV=test` and `mix release` needs to compile for whatever you have set `MIX_ENV` to (`dev` by default). In this case though you are compiling for the default environment when fetching deps, so the compile step that Distillery requests should be effectively a no-op (the compiler will only recompile files if it feels it is necessary, Distillery is not forcing a recompilation). Give your CI, the double compilation is required, since tests and release need to compile for two different environments, but I would suggest the following:

```
mix deps.get
mix test # will do deps.compile and compile for MIX_ENV=test
mix release # will do deps.compile and compile for MIX_ENV=dev (or prod if you aren't setting it to prod)
```

**Comment by xdays** [comment]
Thanks a lot.
