### ISSUE TITLE
Conflicting output_dirs passed to plugin callbacks

### ISSUE THREAD

**Issue by dmarkow** [bitwalker/distillery#367]
### Steps to reproduce

rel/config.exs:
```elixir
environment :prod do
  plugin App.Plugin.Example
end

release :app do
  set output_dir: "rel/app"
end
```

lib/app/example.ex:
```elixir
defmodule App.Plugin.Example do
  # ...
  def after_assembly(release) do
    debug release.output_dir # _build/prod/rel/app
    debug File.exists?(release.output_dir) # false
    debug release.profile.output_dir # rel/app
    debug File.exists?(release.profile.output_dir) # true
    nil
  end
  # ...
end
```

### Description of issue

I've set `output_dir` in my distillery config. When a release is built, it correctly gets put in `rel/app` instead of `_build/prod/rel/app`. I need to modify the release before it's packaged. However, the `output_dir` in the `%Release{}` struct passed to `after_assembly` has `_build/prod/rel/app` hardcoded regardless of what my config's `output_dir` is.

It seems that if I use the `output_dir` value on the nested `%Profile{}` object instead, it resolves to the correct `rel/app` directory. Is there a reason that these `output_dir` values don't match, meaning I should always use the profile's `output_dir`? Or are they supposed to match?

Using distillery 1.5.2

**Comment by bitwalker** [comment]
You should always use the information from the profile for the precise configuration - the release struct contains the initial release configuration (i.e. defaults provided by Distillery or found in the release definition in `rel/config.exs`), and the profile field contains the application of any environment-specific settings to those defaults. Internally it is helpful to maintain them distinctly, and Distillery provides the full configuration structure it uses so that plugins have full access to all the same information.

If you think the docs could be improved, would you be willing to open a PR with those changes? It is helpful to have someone who has run into an issue write the documentation to fill in the gap they encountered since they know best how the docs would have helped them. That said, if you don't have time, I can certainly do so myself :)
