### ISSUE TITLE
How distillery determine the upfrom version when build upgrade release?

### ISSUE THREAD

**Issue by darkbaby123** [bitwalker/distillery#368]
Our workflow is to use git commit id as the part of the app version when deploy staging branch, like `1.0.0+8212c5`. When executing `mix release --upgrade` I found distillery is very smart to get the previous version. But I can't find any details on the documentation. Can you tell me how it works please?

Below are the rules I found:

1. When the new version is `x.y.z+meta` but there's an old version `x.y.z`, it'll be used as previous version (upfrom), even it's not my previous build.
2. In most other case distillery treat my previous build as the previous version.

The reason I want to know this, is because our deployment flow is integrated into CI, so I need a reliable way to get the previous version every time the project builds. I'm not sure if I can rely on distillery to automatically determine the upfrom version, or always specify a `--upfrom` parameter explicitly?

**Comment by up2jj** [comment]
I would like to know this information too. Our CI tool is probably misconfigured and we try to solve the problem with wrong "upfrom" version

**Comment by bitwalker** [comment]
As @up2jj mentioned, you should review the code in `Utils.sort_versions` to see how Distillery orders versions, if `--upfrom` is not set, then it will always use the greatest version according to that sort order.

For purposes of being precise though, I would always provide `--upfrom` if you know the old version when performing the build. You can rely on Distillery to do "the right thing" generally speaking, but that's only if the version you are upgrading from is present in the release output directory, as you pointed out, Distillery will happily upgrade from something arbitrarily older, because it doesn't know that there were other intermediate releases, it just looks at what older releases it has to choose from, sorts them, and chooses the most recent.
