### ISSUE TITLE
Release failed, Duplicated modules

### ISSUE THREAD

**Issue by mvalitov** [bitwalker/distillery#372]
### Steps to reproduce

I encountered such a problem.
when I try to build a release, together with the amqp and floki libraries, I get an error.

my deps list:
```
      {:phoenix, "~> 1.3.0"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.2"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.10"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.11"},
      {:cowboy, "~> 1.0"},
      {:comeonin, "~> 3.0"},
      {:ecto_enum, github: "gjaldon/ecto_enum"},
      {:scrivener_ecto, "~> 1.0"},
      {:amqp, "~> 1.0.0-pre.2"},
      {:timex, "~> 3.1"},
      {:canary, github: "cpjk/canary"},
      {:logger_file_backend, "~> 0.0.10"},
      {:excoveralls, git: "https://github.com/parroty/excoveralls.git"},
      {:distillery, "~> 1.5", runtime: false},
      {:httpoison, "~> 0.12"},
      {:poison, "~> 3.0"},
      {:floki, "~> 0.19.0"}
```

How can I fix this error?

### Verbose Logs

```
...
==> Generated overlay vars:
    release_name=:my_app
    release_version="0.0.1"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=true
    include_src=false
    include_system_libs=true
    erl_opts=""
    run_erl_env=""
    erts_vsn="9.1"
    output_dir="_build/prod/rel/my_app"
==> Copying applications to _build/prod/rel/my_app
==> Generating nodetool
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 9.1 from /usr/lib/erlang/erts-9.1
==> Generating boot script
==> Release failed, during .boot generation:
        Duplicated modules: 
        mochiweb_util specified in rabbit_common and mochiweb
        mochinum specified in rabbit_common and mochiweb
        mochijson2 specified in rabbit_common and mochiweb
```

### Description of issue

- What are the expected results?
- What OS, Erlang/Elixir versions are you seeing this issue on?
```
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.5.2
```
- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)

```
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    default_release: :default,
    default_environment: Mix.env()

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"NpR>I~:?g%`cL/ArR0c?m]h7BaB?c{IJL7u%p1;1Y6pwbad&3w)[K(a/~4a1Qk:_"
end
environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"gQ,N&rZY)E({s];zXvQ~%?*[je5mMsh>A.&6GO8GiX9O;1&XHijI|Jk(5fHc6$HW"
end

release :my_app do
  set version: current_version(:my_app)
  set applications: [
    :runtime_tools,
    :canary,
    :canada
  ]
end
```

- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.

**Comment by bitwalker** [comment]
This is fundamentally a problem with those two dependencies (primarily with `rabbit_common`, since it appears to be redefining modules it doesn't own). Your choices in the short term are to fork one or the other and remove the duplicated modules from whichever dependency takes priority - I would assume `mochiweb` in this instance, so you should fork `rabbit_common` and remove those modules. You should also report this to the maintainers of both projects to see what they think should be done (as mentioned, I think `rabbit_common` is doing the wrong thing here, so I would report it as a bug and request that they rename those modules if they are using them internally for some reason.

Distillery can't actually help you here, since the decision of how to handle this has to be made on a case-by-case basis.
