### ISSUE TITLE
Question about runtime configuration of deps

### ISSUE THREAD

**Issue by predrag-rakic** [bitwalker/distillery#374]
I would really appreciate if somebody could explain reasons for choosing approach recommended for configuring dependencies.

In `docs/Runtime Configuration.md` it says "If you have dependencies which require runtime configuration, you should add them to `included_applications` and start them as part of your supervisor tree..."

Why is that approach preferred over: update application environment in runtime and restart updated dependencies?

For example: If I'm developing application `A` and it depends on applications `B` and `C`.
And if application `B` happen to also depend on `C`.
And I want to dynamically configure `C` from `A`, recommended approach wont work since `C` will be started before `A` because it is `B`'s dependency.

Thank you.

**Comment by bitwalker** [comment]
The recommendation here is to either:

1. If `B` does not include `C`, then include both `B` and `C` in `A`, and perform the configuration of `C` in `A`, before starting `C` and then `B`
2. If `B` includes `C`, then you can just include `B` in `A`, and perform the configuration of `C` before starting `B`

If I understand your proposal, you are suggesting configuring `C` at runtime, and then stopping and starting `C` - but this won't work, since stopping `C` will almost certainly cause `B` to fail (since it expects `C` to be started).

The recommendation in the docs is driven by the need to handle runtime configuration that may determine how the supervisor tree itself is started, in which case it needs to be set in stone before the application starts. Ideally such applications would expose some kind of init callback to dependent applications so that you can do whatever you need to do at runtime to configure it (as Phoenix 1.3+ does), but since that is not yet very common, the approach in the docs works best. If the configuration that you need to change will be picked up automatically (say it's polled every time some event occurs), then you don't need to restart anything, just use `Application.put_env` - but that's only good for a specific case of configuration, and doesn't apply to runtime configuration in general.

Make sense?

**Comment by predrag-rakic** [comment]
Thank you for the clarification.
Yes, it does make sense because I can't think of better way to do it.

But my concern is that this recommendation diverges from OTP convention of managing dependencies (which is really general) and can easily take us to diamond-like situation:
`A` depends on `B`, `C` and `D`.
`B` depends on `D` and follows recommendation, so it starts `D`
`C` depends on `D` and follows recommendation, so it starts `D`
And then while starting `A`, both `B` and `C` needlessly configure and (try to) start `D`. 
`C` probably crashes.

**Comment by bitwalker** [comment]
This recommendation is _based_ on OTP convention. The situation you describe would itself be violating OTP conventions - libraries should never include applications, they should have their dependencies in their applications list, but never in their included_applications list. This leaves control up to the including application. Given the situation you describe:

- `A`, the "including" application, depends on `B`, `C`, and `D` and has them all in `included_applications`
- `B` depends on `D` and has `D` in `applications`
- `C` depends on `D` and has `D` in `applications`
- `A` starts, configures `D` properly for `B` and `C`, starts `D`, then starts `B` and `C` in whatever order makes sense

This is the case where `D` does not expose the "init callback" method I mentioned, in which case when `D` starts, the callback handler (defined in `A` most likely, but possibly `B` or `C`) would be executed, and `A` would not need to include any applications at all.

If this is an umbrella application, where `A`, `B`, and `C` are under your control, and none of them are "libraries" per se, you can still pick one (say `A`) to be the "master" which includes the rest, or even create a new application to be the "master", but I haven't yet encountered a situation where that's necessary. The bottom line is that the only thing using `included_applications` should be _your_ applications, not dependencies. If you know of dependencies violating this rule, let me know, and I'll be happy to open issues/PRs to fix them.

**Comment by predrag-rakic** [comment]
Thank you again, for emphasizing/explaining difference between library and application.

**Comment by bitwalker** [comment]
No problem :)
