### ISSUE TITLE
path to file

### ISSUE THREAD

**Issue by MeterSoft** [bitwalker/distillery#396]
i have umbrella apps.
One of my app has in config file
`config :logger, :request_url,
  path: "log/request_url.log",
  level: :debug,
  metadata_filter: [type: :request_url]`
but after build production reliase i can not find my file log/request_url.log
where is it?

Also when i run `mix release --env=prod --name=posting_matcher` it parse config from all umbrella projects but it has conflict (for example logger setup) It is possible to load config only from released project? not for all

**Comment by bitwalker** [comment]
The path you specified will be in relation to the root directory of the application, in a release, that will likely be `<deploy root>`, but you can confirm the precise path by running your app with `console` or connecting remotely with `remote_console` and executing `File.cwd!`. All relative paths will be relative to that location.

The reason your configs are all merged when you build a release from the umbrella root is because by default, when you create an application under `<umbrella root>/apps`, it will have it's `config_path` in `mix.exs` set to `../../config/config.exs` which is the config at the umbrella root, and that config file includes the configs from all applications in the umbrella. If you want to control this behaviour, you either need to modify how the umbrella config file includes the other configs, or build your release from an application within the umbrella rather than at the root. This is not so much a Distillery thing, as it is a matter of how Mix does configuration, so there isn't really a way for Distillery to do this for you.
