### ISSUE TITLE
Any way to bind ENV variable to config without recompiling project?

### ISSUE THREAD

**Issue by AndrewDryga** [bitwalker/distillery#40]
Hi guys. Im trying to use ENV variables in release, to make sure that I don’t need to re-deploy everything whenever my config changes (for example, DB password).

I’m using distillery, but it should be much different from exrm), I’m trying following steps:

1. Setup config.exs that looks like this (to try different approaches):
  ```
  config :boilerplate, :boilerplate,
    user_test: {:system, "${DB_USER}", "defuser"},
    user_test2: "${DB_USER}",
    user_test3: System.get_env("DB_USER"),
    user_test4: System.get_env("DB_USER") || "default user"
  ```

2. Compile everything
  ```
  MIX_ENV=prod mix release
  ```

3. This compiles all source and `sys.config` looks like expected:
  ```
  [{sasl,[{errlog_type,error}]},
   {boilerplate,
       [{boilerplate,
            [{user_test,{system,<<"${DB_USER}">>,<<"defuser">>}},
             {user_test2,<<"${DB_USER}">>},
             {user_test3,nil},
             {user_test4,<<"default user">>}]}]}].
  ```

4. Start app with `REPLACE_OS_VARS=true`:
  ```
  REPLACE_OS_VARS=true DB_USER="someuser2" rel/boilerplate/bin/boilerplate console
  ```

5. And everything works well, on first start it loads config from environment variables:
  ```
  iex > Application.get_env(:boilerplate, :boilerplate)
  [user_test: {:system, "someuser2", "defuser"}, user_test2: "someuser2",
   user_test3: nil, user_test4: "default user»]
  ```

But it also replaces variables in config and they won’t be able to changed when ENV changes. `sys.config` after step 5:
```
[{sasl,[{errlog_type,error}]},
 {boilerplate,
     [{boilerplate,
          [{user_test,{system,<<"someuser2">>,<<"defuser">>}},
           {user_test2,<<"someuser2">>},
           {user_test3,nil},
           {user_test4,<<"default user">>}]}]}].
```

Futher restart of application with different ENV vars doesn’t change them in settings:
```
iex > Application.get_env(:boilerplate, :boilerplate)
[user_test: {:system, "someuser2", "defuser"}, user_test2: "someuser2",
 user_test3: nil, user_test4: "default user»]
```

So. *Is there any way to read ENV variables without replacing them in `sys.config`*?

**Comment by AndrewDryga** [comment]
Also I know about conform, but maybe there are some simples solutions to just read ENV vars?

**Comment by AndrewDryga** [comment]
Problem might be located somewhere here: https://github.com/bitwalker/distillery/blob/master/priv/templates/boot.eex#L196

Original file is also replaced on second run with REPLACE_OS_VARS

**Comment by bitwalker** [comment]
Generally the `{:system, "VAR"}` convention is used with a config wrapper like [this one](https://gist.github.com/bitwalker/a4f73b33aea43951fe19b242d06da7b9), in which case you do not need to use the interpolation syntax and everything works as you'd expect. This is actually the pattern I'd recommend in general for handling configuration, since it works both with regular config and environment config. However I will take a look at the existing behavior to see if this is intended or a bug, I'm on my phone at the moment so I can't do a more careful review just yet.

**Comment by AndrewDryga** [comment]
Thanks for link. But still is it actually good that each start of application can one-way rewrite `sys.config`?

**Comment by bitwalker** [comment]
A backup is created, `sys.config.orig` prior to replacement, which can be found in `releases/<version>/`, or if you placed your own `sys.config` in the release root directory (i.e. the directory containing `bin`, `erts-*`, `releases`, etc.), it will be placed there instead.

**Comment by AndrewDryga** [comment]
Backup file gets replaced each time you start your application, take look at this code: https://github.com/bitwalker/distillery/blob/master/priv/templates/boot.eex#L218

On second start backup file you `mv` current `sys.config` to `sys.config.orig`.

**Comment by bitwalker** [comment]
Yes, because if you change something in `sys.config` you want a snapshot of the last good config, which is what this does.

**Comment by AndrewDryga** [comment]
Is there any way to preserve original sys.config? Maybe some flag or hook that can copy it before you replace sys.config?

**Comment by bitwalker** [comment]
Probably the easiest way is to create a different suffix for snapshots, preserving the original one as .orig, I can look into that

**Comment by bitwalker** [comment]
@AndrewDryga is it enough to only create `sys.config.orig` if it doesn't exist? I've played around with a few options and that's the only one that makes sense to me. Anything else is overly complicated and not really worth the effort, considering the original `sys.config` can always be obtained from the release tarball under `releases/<version>/<app>.tar.gz`

**Comment by AndrewDryga** [comment]
I think yes, since each next start will replace os vars and write them to system os.

The main thing is that there are more and more people trying to follow 12 factor apps convention (and we have reasons for it :), and behavior when you loose ability to configure app via environment variables after first start is bad, and ambiguous.

**Comment by bitwalker** [comment]
@AndrewDryga Oh that's the only way I configure my apps in production, I just don't use `REPLACE_OS_VARS` with `sys.config`, I use the config wrapper I mentioned above for that. In any case, I'll push a change for this soon.

**Comment by AndrewDryga** [comment]
Can you, please, tell how does this wrapper works internally? Why It doesn't pre-compile values as it happens when you use `System.get_env~ in `config.exs`?

**Comment by bitwalker** [comment]
When you use `{:system, "VAR"}` or `{:system, "VAR", default_value}` in `config.exs`, they are treated as tuple literals when converted to `sys.config` - this isn't because they are treated specially, but just because they are data structures, not function calls like `System.get_env/1`.

At runtime, instead of calling `Application.get_env`, I call `Config.get` for a string value or `Config.get_integer` if I need an integer value, other functions can be easily added to handle other types, but generally I'm covered by those two. `Config.get` under the covers calls `Application.get_env/2`, if the value returned is `nil`, then either `nil` is returned, or the default value if `Config.get/3` was used. If the value returned is not a tuple, then it is returned directly, except for the case of `Config.get_integer`, where the type is checked. If the value is one of the two `:system` tuples described above, then `System.get_env` is called using environment variable name from the tuple, and the result is returned - if the result is nil, either `nil` or the default is returned.
