### ISSUE TITLE
Deployment Timeout update Documentation or Feature request

### ISSUE THREAD

**Issue by noizu** [bitwalker/distillery#404]
### Steps to reproduce

I have a project with a very high concentration of workers per node. ~250-500k. It's commonly an issue that deployments rpc timeout due to, I believe, the default value  set in the priv/*.eex file rpc calls. 

Is there a recommended mechanism for overriding the default timeouts, like can I copy and paste the privs somewhere in my project to override the default implementation or if that is no possible do you have any pointers/suggestions for how you would want me to extend the templates to allow for an override of the default values. 

### Logs
I will look into preparing verbose logs the next time I run a deployment on prod. 
root@stage2-core:/mnt/data/code/lax-alerts/src/ingressor/src# dist/bin/ingressor upgrade 1.1.21
Release 1.1.21 not found, attempting to unpack releases/1.1.21/ingressor.tar.gz
Unpacked successfully: "1.1.21"
Release 1.1.21 is already unpacked, now installing.
escript: exception error: no case clause matching {badrpc,timeout}

### Description of issue

 **Outcome** When deploying a hot upgrade against a environment with high concentration of worker processes per supervisor I frequently see a failed deployment due to an uncaught {bardrpc, timeout}
 **Expected** I would expect to see no time out error or have the ability to modify the default time out behavior to accommodate my server's characteristics.

**Comment by bitwalker** [comment]
The new stuff in master has an `:infinity` timeout for the `rpc` command. I may add a `--timeout` flag in the future, but right now it does what you want. That said, I haven't tagged 2.0 for a release yet, so you would be living on the edge a bit. Otherwise, your other option is to edit the `nodetool` escript, and just overwrite the one located at `<deploy_root>/bin/nodetool`, or just edit it in-place. Since your error occurred in a release upgrade installation, you will want to edit the `release_utils` escript as well. Both scripts in 1.x are written in Erlang, in 2.x they are merged together into a single Elixir script.

If you'd like to help make the timeouts for various operations in the 2.x script configurable, I'd be glad to open a new issue for that and give you some pointers though!

**Comment by bitwalker** [comment]
Given your current situation though, you may want to edit the existing scripts, and wait until I cut a proper release for 2.x before you go down that road.

**Comment by bitwalker** [comment]
I'm effectively sponsored via my employment with DockYard, so the answer to that question is a bit clouded, but no I usually don't as a rule on all my open source projects - as long as I can keep paying the bills with my day job, I enjoy working on this stuff pro bono :) (thanks for asking anyway!)
