### ISSUE TITLE
Put a release in /opt with no write permissions

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [bitwalker/distillery#421]
### Steps to reproduce

- Create a linux user with only permission to read and execute in the directory of the release
- Start the release with such user
- Get error "permission denied to create `var` directory"

### Description of issue

I would like to be able to configure what parts need to be writable.
Following the [permissions section in FAQ](https://github.com/bitwalker/distillery/blob/master/docs/faq.md#permissions), I see that I can set a different path for variable and for the erlang cookie.
However, it's not clear what do I have to make writable for upgrades _and_ if I can configure that part.

Is there any place where I can find more information?

Based on debian policy, `/opt` should be "readonly" once the application is installed in there (nothing should write beside the installation process), but it's hard to achieve it if the release requires to write there.

**Comment by bitwalker** [comment]
You can set `RELEASE_MUTABLE_DIR` to point somewhere in `/var` rather than in the root release directory as it does by default. With that set, the only time write permissions are needed to the release directory are when you are applying hot upgrades, in which case the entire release directory can be potentially written to, since the release is unpacked as a tarball relative to the release root directory, by the running node and so with the permissions of the user that node is running as; and depending on the contents of the release tarball, anything under the release root directory may need to be written to.

**Comment by Fire-Dragon-DoL** [comment]
Thanks for the details, that's a very helpful tip to organize the permissions in /opt. Would you like if I add the part regarding hot upgrades to the readme?

**Comment by bitwalker** [comment]
@Fire-Dragon-DoL Sure! I'd be happy to improve the docs to make this more clear
