### ISSUE TITLE
Question: Decouple from Bash?

### ISSUE THREAD

**Issue by beardedeagle** [bitwalker/distillery#422]
I haven't looked through all of the `*.sh` scripts in this repo, but how resistant to decoupling distillery from bash and just using sh instead would you be @bitwalker?

**Comment by bitwalker** [comment]
Supporting POSIX shell was originally a design goal, but I found out at some point that while I thought we were POSIX-compatible, it turns out that we are dependent on some features which are not supported by all `sh` implementations (or those shells which `sh` is symlinked to on modern OSs). This has been brought up before, so you can hunt around for more details, but in a gist, the issue is that support for the public shell API which Distillery exposes for custom commands and hooks, can only be done if the `sh` implementation supports sourcing scripts with arguments. Bash allows this of course, as it is actually a bashism, not a POSIX-compatible feature, as do some `sh` implementations, but the main reason why this issue was discovered is because `sh` is symlinked to `dash` on Ubuntu, which explicitly does not support this feature. I've done some work to try and work around our usage of this feature, but it effectively would require deprecating the shell API entirely, which I'm not willing to do.

Rather than use `sh` and have Distillery scripts break on incompatible systems, I changed the shebang to explicitly use `bash`, so that the scripts will work as long as the system has bash installed (which is virtually all of them). There is a shim script which does use `sh`, to determine if `bash` is unavailable and print a friendlier error message, but the bulk of the scripts depend on bash.

So, I'm not resistant to being POSIX-compliant, but I don't think it is achievable with the feature set Distillery provides today. If you can find a solution that works around the sourcing-with-arguments issue, I'm certainly happy to switch back to `sh` and remove the dependency on `bash`.
