### ISSUE TITLE
Why do I need to use -cookie?

### ISSUE THREAD

**Issue by ruslansavenok** [bitwalker/distillery#428]
[Distributed erlang docs](http://erlang.org/doc/reference_manual/distributed.html#security) say, that if cookie wasn't provided, it writes one to `$HOME/.erlang.cookie`.

But if you'll try to remove `-cookie` from `vm.args` template using `set vm_args: "rel/vm.args"`, it will show an error a [secret cookie must be provided....](https://github.com/bitwalker/distillery/blob/fa6777fdc0c61aa8fcad54ffaabbb6829dd4fb38/priv/libexec/config.sh#L195)

Why distillery doesn't allow to run build release withot a cookie?

**Comment by bitwalker** [comment]
You need to use `-setcookie` in your `vm.args` file, whether the default, or one you provide with `set vm_args`; alternatively you can provide a cookie via `$HOME/.erlang.cookie` with the right permissions set. If you are using `-cookie`, that is not the name of the flag, so it is not finding the cookie and exiting with that error.

The cookie is required for releases built by Distillery, as it is a requirement for running a node with distribution enabled, which in turn is required in order to interact with the node (to open a remote shell, tell a running node to stop, execute a command, etc.). Distillery doesn't require a cookie at build-time, but it does require one at runtime.

**Comment by ruslansavenok** [comment]
@bitwalker I understand that cookie is required to communicate between nodes. 

But I don't understand why it's required by distillery startup script if one is created automatically by erlang.

For example, when you start a node `erl -name test_node`, it will create `$HOME/.erlang.cookie` file if one doesn't exist. As described in [docs](http://erlang.org/doc/reference_manual/distributed.html#security)

I removed that if from `app_name.sh` in my `_buil../rel` folder and it does work the same, the cookie is automatically created.

```
cat $HOME/.erlang.cookie
cat: /Users/ruslansavenok/.erlang.cookie: No such file or directory

PORT=4000 _build/dev/rel/test_app/bin/lib_ten start

cat $HOME/.erlang.cookie
HMASDQVLHAQNKAOYMMAD
```

**Comment by bitwalker** [comment]
The start script makes this restriction because if the file doesn't exist or we have insufficient permissions, the error which results is very user-unfriendly. This error makes it clearer what is expected. What we could do is if the file doesn't exist, run `erl -name "$NAME" -s erlang halt` and then check again (trapping the error of course if `erl` is unable to create the file due to permissions). I'll make that change.

**Comment by bitwalker** [comment]
See 31522bd
