### ISSUE TITLE
In Umbrella, when building 1 app, code for other apps compiles too

### ISSUE THREAD

**Issue by psteininger** [bitwalker/distillery#432]
I have 2 apps in my umbrella, both Phoenix APIs, meant to be deployed on separate servers. I want to build them one by one, on CI to save unnecessary cycles and time. So I run the 2 in sequence:
```
MIX_ENV=prod mix release --env=prod --name library
MIX_ENV=prod mix release --env=prod --name delivery
```
to each I also add ENV vars for secrets_base, db connection info, etc. However, it looks like the first release run does all the compiling for both apps. This also creates a sys.config that has data for both apps, which is ok, but the values are wrong.

So I would like to find a way not to compile `delivery` app code when `library` release is built OR have a way to discard `delivery` compiled code before I run  
```
MIX_ENV=prod mix release --env=prod --name delivery
```

Here is my setup for releases:
```
release :delivery do
  set version: current_version(:delivery)
  set applications: [
    :runtime_tools
  ]
end

release :library do
  set version: current_version(:library)
  set applications: [
    :runtime_tools
  ]
end
```

Thanks for looking into it and advising on workaround/solution

**Comment by koudelka** [comment]
also quite interested in this 👍

**Comment by psteininger** [comment]
so far, my workaround was to create a set of ENV vars for each app like so:
```
${APP_NAME}_DB_USERNAME="..."
```
and reference it in `config.exs` via 
```
System.get_env("LIBRARY_DB_USERNAME")
``` 
"library" is one of the apps

**Comment by bitwalker** [comment]
Ultimately this falls on Mix to identify when the app needs recompilation, Distillery doesn't make those decisions, it delegates this work to `mix compile`. If you are building the release from the umbrella root (I'm assuming you are using an umbrella here), then it is always going to compile all umbrella applications on the first run, and reuse the compiled artifacts on the second. Your workaround for configuration is essentially forcing Mix into recompiling the app which has had it's effective configuration changed (i.e. the value of the environment variable is different in that apps config, and so it recompiles it).

If you need to break up the compilation, then you can try building the release from the app's project directory, rather than the umbrella root, e.g. `pushd apps/library; mix release; popd; pushd apps/delivery; mix release; popd`. Ultimately though, there isn't anything Distillery can do about this, as it doesn't make any decisions about the build itself, Mix does.

**Comment by psteininger** [comment]
Thanks for the explanation. I chose the route of each app having separate
ENV cars, and got the wrapper scripts to set the vars upfront for all apps
inside the umbrella.

I will try to describe the journey and setup in a blog post soon.
