### ISSUE TITLE
How to have one one merged config.exs file

### ISSUE THREAD

**Issue by stef-otpyrc** [bitwalker/distillery#486]
### Question

With 2.0.0.rc2, I was generating one aggregated config file that I was using with the config_providers. Since https://github.com/bitwalker/distillery/commit/2986e088f71a5d5e94beb897b2bf2d0720630eb6#diff-15ab018afaf02837b0047539141c7e28 the aggregated config file isn't generated.
I saw that I can copy the config file using overlays, I am working on an umbrella project with a lot of config.exs (and prod.exs) files. How should I do?

**Comment by bitwalker** [comment]
Distillery isn't going to generate a combined config file any more. The preferred method for using the Elixir provider is either writing a config.exs specifically for bundling in the release, and including it with an overlay; using an overlay to copy a specific config.exs into the release; or using an overlay to copy your entire config folder into the release.

In your case, it really depends on how much of what is in those config files is static vs dynamic information - if only a few parts are going to change at runtime, you are better off writing a single config.exs with those values specifically for the release, and packaging it with an overlay. Otherwise, you will need to use overlays to select one or more of the configs you need at runtime.
