### ISSUE TITLE
add an option to not start as a node ?

### ISSUE THREAD

**Issue by jlirochon** [bitwalker/distillery#497]
I had a use case where I needed to disable `epmd` and didn't want the app to start as a node. 

Distillery forces you to have `-name` or `-sname` in `vm.args` so I finally commented [this line](https://github.com/bitwalker/distillery/blob/b4a9ab4b86984a437b7e555596ccd91f68e83a36/priv/libexec/config.sh#L123) to make it work.

I don't know if it makes sense, but maybe an option could be added to start the app without configuring the node ?

**Comment by bitwalker** [comment]
Distribution is required in order to interact with the node - in theory, in cases like `foreground`, you could run the release without distribution, but that still comes with some caveats. In cases like `start` though, we require the ability to communicate. Since interacting with the running release in general is extremely common, this has been pretty far down the list of priorities for me.

I'm open to considering support for running without distribution enabled - but it implies a lot of additional complexity; since we need to handle the case where commands requiring communication with the running node produce a friendly error, as well as handle the case where it is not intended to disable distribution, but things like `-name` or `-setcookie` are missing - that is a lot of extra conditional logic that I'm afraid will be easy to get wrong. It has been preferable (easier to maintain) to assume that it is required except in the few cases where we know we can get away with not requiring it (namely custom commands).

From my perspective, there are easier ways to accomplish the same task, for those cases where you want to disable distribution for some reason - disabling epmd will prevent inter-host distribution, as will setting the hostname portion of `-name` to `127.0.0.1` or `localhost`; setting a unique node cookie will prevent any nodes on the same host from talking to each other because they cannot authenticate. Generally, from an ops perspective, you'd want to drop any network traffic to/from a host that is not explicitly allowed, which is generally my recommended approach in this situation.

I guess I'd want to start by understanding why one of those approaches is not workable, or rather, what your use case was. I understand convenience is desirable, but the cost in this case likely outweighs the benefits, so I want to be sure the reasoning is sound for undertaking a change like this.

**Comment by jlirochon** [comment]
You're right, my use case is too specific. It's worth it only if it's a quick win. As too much changes are involved I'm closing this issue.

I was testing [Serverless Docker Beta](https://zeit.co/blog/serverless-docker) from ZEIT. In this context:
- forget about connecting nodes
- forget about long living applications culture (they recycle containers in a matter of minutes)
- Elixir can still be a language of choice
- Releases still make sense because they produce a minimal Docker image

My problem was that ZEIT implemented an **Automatic port discovery** feature, and as you can guess, it always discovers epmd port instead of Phoenix port. Explicit configuration is not available at the moment, so I had to disable epmd and was sad to comment distillery code. [Long story here](https://spectrum.chat/?t=59344a9f-06e9-42ed-a1e8-7b3deda9376e).

The easier ways you mention doesn't work in this context, but anyway a better way to solve this is having ZEIT disable the **Automatic port discovery** in favor of a configurable port.

**Comment by bitwalker** [comment]
Ah I see - disabling `epmd` alone should be enough, where there issues with just passing `-no_epmd` in your `vm.args` or via erl opts?

**Comment by jlirochon** [comment]
I was not aware of this `-no_epmd` flag, I didn't find it in the doc.

But with this `vm.args`:
```
-name now@127.0.0.1
-setcookie ${NODE_COOKIE}
-no_epmd
```

It gives the following error and exits 1:
```
Protocol 'inet_tcp': register/listen error: {noproc,{gen_server,call,[erl_epmd,{register,now,33581,inet},infinity]}}
```

With `-start_epmd false` it gives this error instead:
```
Protocol 'inet_tcp': register/listen error: econnrefused
```

**Comment by bitwalker** [comment]
Ah, I think you have to provide an alternative epmd module when you use `-no_epmd`. [This article](https://www.erlang-solutions.com/blog/erlang-and-elixir-distribution-without-epmd.html) has the code to do that, and you could tweak it as necessary. You'd just need to add it to your project, and add the appropriate flags to `vm.args`.

**Comment by jlirochon** [comment]
Very interesting article, thanks for the link.

But honestly, not starting as a node seems the right way to solve it: implementing a custom `epmd` sounds overkill since I don't need distributed erlang for this particular deployment. Feel free to correct me if I am missing something about `epmd`.

Thank you for your kind support, I learned things :)
