### ISSUE TITLE
Support for .iex.exs in remote shells

### ISSUE THREAD

**Issue by naps62** [bitwalker/distillery#539]
In a regular Elixir project, we can use `.iex.exs` to customize the prompt, add some aliases, etc.

Is there anything similar we can do to achieve the same effect when connecting to a remote_console of a distillery release?
I'm asking here after two long googling sessions where I could find no occurrences of anyone asking this question

**Comment by bitwalker** [comment]
Remote shells use your local `.iex.exs` rather than the one on the server, if I remember correctly. Is that not working for you? If not, have you tried placing `.iex.exs` on the server in the home directory of the user the release is run as?

Once we pin down which method works, I can make sure it gets documented :)

**Comment by rodrigues** [comment]
At the deployment target I've added a `~/.iex.exs` file, and it worked when I've ran `.../bin/MYAPP remote_console`
