### ISSUE TITLE
To run distillery build on dynamic port.

### ISSUE THREAD

**Issue by zeroshree** [bitwalker/distillery#674]
**This is not an issue** 

How can I run my build with dynamic port.

 _build/$buildenvir/rel/my_api/bin/my_api start

where buildenvir= dev, preprod and production

it's running on 3000 port. I have created one build server integrated with Jenkins. I have 3 environment dev, preprod and production all them are running on 3000 port. 

but in build server I want to run on dynamic port like 3001 ,3002 without changing in code base.

Please let me know. Thanks a lot for creating distillery it's amazing.

**Comment by bitwalker** [comment]
You would need to set up your configuration to pull the port from an env var or some other dynamic source, rather than from a hardcoded value. 

This tracker is primarily for bugs and feature planning though, so this is a better question for [ElixirForum](https://elixirforum.com/) or StackOverflow. I'm going to close this in favor of posting this question in one of those places.
