### ISSUE TITLE
Add documentation about docker / vagrant

### ISSUE THREAD

**Issue by VladShcherbin** [bitwalker/distillery#74]
From the distillery documentation, you can get a feeling that it is super easy - just add a package, add some configuration and run a console command.

Unfortunately, there is a very important note - your app must be compiled in the same environment as your production server. This step is almost missing in the docs and reading tons of information about VM's (virtual machines) is overwhelming for people, who didn't use VM before.

It would be super awesome to have a chapter or even this issue, where every novice could possibly find quick answers w/o wasting days googling.

---

The task is to setup a basic app (phoenix app), make a release in VM and deploy it to production server. Since we have a chapter, how phoenix app has to be configured in the docs, we only need to setup a VM, make a release there and deploy to production server.

The production server has ubuntu 16.04. The dev server has OS X. The VM options are - vagrant and docker. If I understood correct, vagrant runs os in you prod os while docker uses just your prod os.

So, the first questions are:
1) vagrant or docker, cons and pros
2) dev server has to be the same as production one, what has to be the same (os, cpu, ram, os packages) ?
2.1) do we need to setup docker / vagrant on production server or just copy the release tarball file?

**Comment by bitwalker** [comment]
Sure I can see this being helpful to have some better documentation around. My personal feeling is that it's easier to setup and automate things with Docker versus Vagrant, Vagrant also has additional dependencies which make it a pain to install if you are using it with just one project.

Only the OS, architecture (32bit vs 64bit), and any system libraries which your app depends on (i.e. OpenSSL) need to be the same between your build server and production. The latter may not be as strict as the first two, but I generally try to keep them the same to be safe.

You build the release using Docker, then copy out the tarball, then deploy the tarball to your production server, you don't need to deploy Docker/Vagrant/etc. to your production server.

I've been thinking about building a Docker plugin for Distillery, but that's still a little while from now, need to find some spare time first ;)

**Comment by VladShcherbin** [comment]
Okay, so the recommended VM will be docker.

1) Is there any image example for docker? If we choose [ubuntu image from hub](https://hub.docker.com/_/ubuntu/), do we need it be the exact version on prod & dev (xenial-20160818 for example) or any 16.04 will be okay?
2) If we just copy the tarball and not the whole docker container, how can we be sure that it will use the same version of packages (OpenSSL, etc)?

**Comment by bitwalker** [comment]
1. Any 16.04 is fine.
2. How you deploy depends on your production environment. If you are running containers in prod, you would build an image via Docker and push that to an image repository your production environment pulls from. If you are running manually managed hosts, then you would write a Dockerfile which installs the same dependencies as you run in production, build the release in the image produced by that Dockerfile, copy the tarball out, and push to production.

If you are not running the container in production, then you do have to make sure you keep the Dockerfile in sync with what you are running on your prod hosts, but that's no different than making sure you keep your prod hosts in sync.

**Comment by merqlove** [comment]
I found that mostly you can build safe locally with crossOS support (with NIF's recompile inside build container).  
But sometimes especially on `Ubuntu`, we can have different from `OSX` Erlang Kernel version. It give us strange errors.
In this case i found local or `CI` docker build in the same environment as production really helpful.

Example:
https://github.com/merqlove/elixir-docker-compose

**Comment by dropfen** [comment]
+1 for docker

**Comment by johannesE** [comment]
> How you deploy depends on your production environment. If you are running containers in prod, you would build an image via Docker and push that to an image repository your production environment pulls from.

It seems to me that I'd lose the built-in upgrade mechanism if I use docker this way. I'd have to reinvent the wheel with docker machines (one container taking over from the other, losing all data which was in memory, ...). Am I wrong?

**Comment by dropfen** [comment]
@johannesE not necessarily. 
Docker is just a container, where your app runs. So instead of deploying the whole container, one could just deploy the release to that container, and the app would take it and upgrade itself. 
But sure, deploying an image, would result in losing state of the old container, thats true.

**Comment by johannesE** [comment]
@dropfen That is a good idea, yes, thank you. I only had a crash course in docker and mistook container for image. So what you are proposing is to prepare a container and run it on production. The upgrade process would work as usual inside that container (e.g. git pull, build release, upgrade) (or copy the tar into the container, and upgrade). I'm gonna have to try this tonight. 🙃

**Comment by merqlove** [comment]
@johannesE i think upgrading from prebuilt tar in this case is better (safe way).
--
Best regards,
Alexander Merkulov

**Comment by dropfen** [comment]
Additionally if some one is interested, there is this platform *flynn*. Its based on docker and gives you a lot of nice tooling. (postgres, git-receive, clustering) 

Here is an article about phoenix deployment with flynn:
http://nsomar.com/how-to-use-flynn-to-deploy-a-phenix-app/

For now, there is only one heroku buildpack for phoenix, which you can use to deploy your app, but its imaginable how one could extend it and deploy upgrades to the cluster with docker containers which are also supported. Anyway its worth to look at it.

**Comment by bitwalker** [comment]
Just to chime in here, but if you opt-in to using Docker for deployment, you implicitly opt-out of hot upgrades (using the Erlang release mechanism that is, you can still do things like A/B or blue/green deployments). They are fundamentally incompatible. This tradeoff is perfectly fine, but if you need hot upgrades for some reason (which I would generally challenge, as not many situations *really* require them), then Docker is not an option, and you'll want to deploy those applications to hosts you manage more manually. This is in fact what we do at my office, we have some applications which use hot upgrades, and run on their own cluster of EC2 instances, and the vast majority of everything else runs under Kubernetes/Docker.

**Comment by coryodaniel** [comment]
@bitwalker In the case you were doing web socket connections you would need to hot upgrade so that users wouldn't see a service interruption, correct?

**Comment by bitwalker** [comment]
@coryodaniel Depends on how your application is written, it's far easier to have websocket clients reconnect if they are disconnected for some reason, which would result in effectively zero service interruption (I suppose this may depend on the use case as well, but I don't have a good contrary example at the moment). Another approach is to drain connections from one server to another, and then shut down the first one when the connections are drained, or when too much time has passed. In other words, there are other approaches to preventing server restarts from impacting users, and while hot upgrades is definitely one of them, it's not the only tool for this kind of thing.

**Comment by coryodaniel** [comment]
@bitwalker connection draining is a good simple solution!

**Comment by merqlove** [comment]
Also, with Phoenix you have auto reconnect option.

Best regards, 
Alexander Merkulov

**Comment by johannesE** [comment]
So I managed to implement a first solution. You can find it here: https://gist.github.com/johannesE/7ee81d90d0934a70bd14350c562c9366
The upgrade process is not in there yet. It basically just runs the application with a postgres database.

**Comment by dropfen** [comment]
@bitwalker whats the problem with upgrading the release inside the container, if the production container is just the runtime wrapper, which has access to the `rel/` folder. I mean just a simple alpine container, which runs the application in its scope.

I mean the builder (container), could build the release local or on the server, at the end the production container could just take the new release from the mounted folder and perform the upgrade, could't it?

This was my idea [here](#issuecomment-257274154)
I appologies, if this wont work

**Comment by bitwalker** [comment]
@dropfen My opinion is that Docker-based/containerized applications are meant to be immutable, i.e. easily replaced, treated as cattle vs pets. Hot upgrades in Erlang are very much of the opposite mindset, in other words, they are treated as pets vs cattle, generally manually managed, and the upgrades are themselves carefully designed/curated. 

The fact that changes to the filesystem/environment in Docker images are transient (i.e. they are reset if the container is restarted) is just the nail in the coffin for using them with hot upgrades. At any time your container host could go down, and if that happens, you've lost all your state since that image was built. It is far better to design Erlang applications which will run in a container to be easily killed/replaced, because it is not only trivial to scale such applications, it becomes much easier to automate and orchestrate those applications. Containers are just a poor match for hot upgrades - I think it would end up being more pain than it's worth to make that work well.

**Comment by bitwalker** [comment]
@johannesE Your example does not use releases, so it's not particular well suited for Distillery's documentation. Here's an example Dockerfile similar to what I use in production at work:

```Dockerfile
FROM bitwalker/alpine-erlang:latest
ENV MIX_ENV=prod \
    TERM=xterm \
    APP=myapp \
    APPVER=0.1.0

EXPOSE 5000

WORKDIR ${HOME}

COPY . .
RUN \
    echo "@edge http://nl.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk add --no-cache --update --virtual .build-deps \
      elixir@edge \
      git && \
    mix local.hex --force && \
    mix local.rebar --force && \
    mix do compile, release --verbose --env=prod && \
    mkdir -p /opt/$APP/log && \
    cp rel/$APP/releases/$APPVER/$APP.tar.gz /opt/$APP/ && \
    cd /opt/$APP && \
    tar -xzf $APP.tar.gz && \
    rm $APP.tar.gz && \
    rm -rf $HOME/* && \
    apk del .build-deps && \
    chmod -R 777 $HOME && \
    chmod -R 777 /opt/$APP

WORKDIR /opt/$APP

CMD ./bin/$APP foreground
```

We have a CI process which automatically builds and publishes the images to a repository, which in turn triggers deploys to dev. How you set that part of it up really depends on your infrastructure.

**Comment by dropfen** [comment]
@bitwalker Thank you for your response.

> The fact that changes to the filesystem/environment in Docker images are transient (i.e. they are reset if the container is restarted)

Thats true, but my suggestion was to use the container, which would access the shared volume with the latest releases in it and run it. So there would be no state in the container, it would be just the runtime environment. And if it crashes, just run it again. We could then share some release history.txt with the latest and previous release information. After every successful upgrade the container would commit to that file and read from it on restarts.

The benefits of running your app inside a container is scoping your environment variables, and use some other docker features, like linking..

By the way, it would be interesting, to perform release upgrades from inside the app directly, over the UI ;). And then, it doesn't matter where the release is running in.

**Comment by bitwalker** [comment]
What you suggest should work in theory, but I guess my take on containers is that they aren't particularly appropriate for apps like that (see the whole discussion around 12 factor apps, particularly [this page](https://12factor.net/processes) for the point of view I'm coming from). 

My primary reasons for using containers/Docker in the first place is for the purpose of automation/orchestration, and the approach you suggest actually would make it more difficult for me to achieve those goals (namely autoscaling, A/B deployments, etc.). If I need hot upgrades (which we do for one of our systems), they live on their own cluster of VMs, and we manage them more manually, but they have at least the level of isolation you described because only one application runs on any given VM. In any case, I'm not saying you *can't* run releases with hot upgrades in containers, but I do think that it's a whole lot more effort than it's worth to do so, and would recommend alternative approaches if possible.

**Comment by dropfen** [comment]
Got your points, thank you for taking the time to explaining it. I guess my (current) cases are not that demanding. I am just trying to run everything in containers on a single host, and linking them together, so upgrading inside a container would work, if needed. If I would have to manage a node cluster, the clean VM way would make more sense to me also.

**Comment by johannesE** [comment]
After reading all that stuff about hot upgrades (thank you!), I think we should rather do a [chef](https://learn.chef.io/) documentation..

**Comment by jeroenhouben** [comment]
I've been following this thread and just want to sum up my "key take aways". Please reply if you think they are incorrect.

- OTP apps have really cool hot code upgrade capabilities, which:
  - you probably don't need
  - are not trivial to master
  - require a very different deployment approach than is common these days
  - is not compatible with container based / Heroku style hosting

So if you are coming from ruby, nodejs or something like that you can just use more or less the same deployment techniques. Only caveat is that you need make sure the compiled code can run on the host's OS

**Comment by bitwalker** [comment]
@jeroenhouben I would agree with those statements, more or less. I would say that hot upgrades are worth looking into if you are building an application where the complexity is a worthwhile tradeoff, but those kind of applications are probably not nearly as common as the average case.

**Comment by dropfen** [comment]
The communication systems which are build on top of OTP, are separated into many small pieces of different functionalities. So, you can upgrade this parts one by one easily. And its very useful to stay always online. But the most of our Apps don't need it, so we can just "replace" the instances like an html file.

But, I definitely see a great potential of this feature also for normal WebApps. Especially for GUI-Driven Systems, like Drupal. Drupal has this philosophy "there is a module for that". And any module can have its own DB-Configuration Settings. The problem with it is, that your App gets really slow, because of all the checks against the DB configurations. So for scaling there are things like Vanish the first choice, which makes your Site *static*.

And here I see a great potential for the BEAM. Some one could build a DB-Driven System, which would compile and upgrade the code on the fly. Something like *DB-Driven-Metaprogramming*
Theoretically this could work. We would write mini Elixir Projects / Modules, which would implement some default functionalities like install / uninstall and have an API to the system. This would allow you to upgrade the system, create models, layouts, logic and so on. But more important, it would be still very fast, and reproducible.
