### ISSUE TITLE
Project update

### ISSUE THREAD

**Issue by matheuscamarques** [bitwalker/distillery#746]
I found a lot of interesting things in this repository which I would like to use to distribute applications, but I would like to understand how is the development of this project if there are updates or is it a discontinued project already?

**Comment by wgordon17** [comment]
@bitwalker is this an abandoned project?

**Comment by bitwalker** [comment]
It has been superseded by the releases functionality integrated into Mix in Elixir 1.9. I no longer use it myself and am not actively maintaining it, but I am open to adding more maintainers if there is interest.

**Comment by wgordon17** [comment]
@bitwalker thanks for the reply. As a newbie to Elixir, everything I've been reading about was referencing `distillery`, so I'm glad to hear that the functionality is part of Mix now 👍

**Comment by bitwalker** [comment]
It was the go to solution for a long time, unfortunately a lot of blog posts and such have never been updated to mention the built-in release functionality (which was largely derived from Distillery, but does do some things a bit differently). 

In any case, my recommendation is to always use and refer to the out-of-the box tools first before looking at third party tools like this one, even if you read a recommendation otherwise. In the early days of Elixir, much was missing from the standard library and Mix, so many tools and libraries sprung up to fill the void, but over time they become redundant, so it always pays to see if you can avoid the extra dependencies first before looking elsewhere. Anyway, you didn't ask for my advice, but hopefully as someone new to the language, you find it helpful 🙂

**Comment by bautrey37** [comment]
@bitwalker Can you update the top of the README with this information?

**Comment by bitwalker** [comment]
@bautrey37 Done
