### ISSUE TITLE
[minor] Should rel/config.exs live elsewhere?

### ISSUE THREAD

**Issue by martin-langhoff** [bitwalker/distillery#81]
As an early user of Distillery, I am finding a (minor) inconvenience that the `rel` dir holds both output and an important file which should be tracked in version control (ie: git). 

Should `rel/config.exs` live elsewhere? Maybe `mv rel/config.exs releaseconfig.exs` ?

**Comment by schnittchen** [comment]
Or `distillery_config.exs`

**Comment by bitwalker** [comment]
I would prefer to leave anything release related in `rel`, but I am looking in to moving the release artifacts to `_build`, since it seems to be a more appropriate place for them.

**Comment by martin-langhoff** [comment]
Sure, a move to `_build`  would work for me too. +100 :-)

**Comment by bitwalker** [comment]
I have a couple of improvements I plan on doing around this, and I'm curious on your thoughts:

- Move build output to `_build`
- Add task `mix release.console` which ensures the release is built and runs the release console
- Add task `mix release.foreground` which ensures the release is built and runs the release in foreground mode
- Make it possible to point `mix release` at a tarball when performing upgrades, so that you only have to save the tarball from the last release in order to generate an upgrade.

The question around what to do with the tarballs is the outstanding one for me. Burying them in _build is not really any worse than where they are located in rel today, but especially considering the last point on the list above, I think of the release tarballs as a more important artifact produced by the release process, and I'm wondering if there isn't a better place to put those.

Thoughts?

**Comment by schnittchen** [comment]
I could see releases living in fex. Amazon s3, which would require some tooling on the server side.
How fixed do you see the release store API, could it easily be adapterized?

**Comment by martin-langhoff** [comment]
@bitwalker - +10 on the move to `_build`,+1/ neutral on all the other ones (they don't affect me :-) ).

**Comment by bitwalker** [comment]
@schnittchen That's an interesting idea I hadn't considered. Do you have thoughts on what an adapter API might look like?

**Comment by schnittchen** [comment]
I assume distillery is fetching/pushing named release files and doing something like "is there a release of version X? What versions are there?" which for flexibility could be just "tell me all the filenames you see, I'll parse them myself"

**Comment by bitwalker** [comment]
@schnittchen Would you mind opening a new issue with that as a feature request? It'll be easier to track there and we can open it up to discussion as an RFC of sorts.
