### ISSUE TITLE
Question on rel/config.exs

### ISSUE THREAD

**Issue by cjimison** [bitwalker/distillery#89]
### Steps to reproduce

No Steps to Reproduce .. This is more of a question/feature request.  However I am on Distillery 0.9.9.

### Verbose Logs

No logs

### Description of issue

Hi Bitwalker,

First let me say how much I LOVE distillery.  It is really awesome and I have two questions for you:

1) In the rel/config.exs file, is it possible to set the applications based on the environment type?

For example when I make a dev build I would like to include :debugger and :observer however when I make a release build I don't want them in there (release builds go to my production server which doesn't have wx install for example)

2) In the rel/config.exs file, is it possible to set included_applications as well?  When I do the following I get an error:

release :my_app do
    set version: "0.0.1"
    set included_applications:
    [
        :some_other_app
    ]
    set applications: 
    [
        :my_um_app
    ]
end

==> Failed to load config:
    unknown release config setting `included_applications`

Thanks!

**Comment by bitwalker** [comment]
I need to make an adjustment to the way applications in the config are handled, but with the way things work now, you can just do `set applications: [:observer, :debugger]` in the dev config and they will be added to the release for dev, but not for any other profiles. Included applications are currently not supported, but for good reason. Is there a reason you are using `included_applications` instead of `applications` with `some_app: :load` to include an application in the release but not start it? You have to be very careful with included applications because it means the including application has to be responsible for the included application's lifecycle, and no other application can include it or have it in their applications list.

**Comment by cjimison** [comment]
Good to know about the dev config.  I must have missed that in the docs.

As for the “included_applications” it is really about transitive dependencies with poor hygiene.  I really like the warning on missing deps however I see the following:

==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :covertool
    :proper
    etc, etc

This is due to some transitive deps I am using that are not tagging them with the "only test flag”, etc.  That warning has caught errors in my application so I don’t want to turn it off, and I was hoping to not have to fork these projects and fix each one (In my project I have some 10 different deps that has this issue last time I counted).

I don’t really have a good “technical” reason to throw them in the included_applications other than I am a big believer in being warning free without cheating by just turning them off :P   Maybe an ignore list that I could hand curate so I can explicitly say “Yes I know this specific package is not in the applications and I am cool with that, but anything else please let me know” would be great!

But just to say it again … Distillery is awesome!  I was able to simplify my EXRM based project by an order of magnitude and the whole dev team is very grateful (we implemented many of the concepts you have in Distillery but not nearly as cleanly or well thought out).

**Comment by bitwalker** [comment]
You can put `config :distillery, no_warn_missing: [:cover, ...]` in your `config/config.exs` and those applications will not give warnings :)

Thanks for the kind words as well, it's great to hear Distillery has been well worth the switch, feedback like that keeps me motivated :)
