### ISSUE TITLE
Can't start app after hot code upgrade

### ISSUE THREAD

**Issue by szlend** [bitwalker/distillery#91]
The Distillery start script relies on `releases/<ver>/<app>.rel` existing [1]. But when you do a hot code upgrade, it performs erlang's `unpack_release` which deletes `<app>.rel` [2].

[1] https://github.com/bitwalker/distillery/blob/3dd1f196dff64b57703c441592312e8a7c85eb23/priv/templates/release_utils.eex#L9
[2] https://github.com/erlang/otp/blob/3b7a6ffddc819bf305353a593904cea9e932e7dc/lib/sasl/src/release_handler.erl#L854

**Comment by szlend** [comment]
A simple fix is to replace

```erlang
{ok, [{release,_,_,Apps}]} = file:consult(filename:join([RelDir, RelFile]))
```

with 

```erlang
{ok, [{release,_,_,Apps}]} = file:consult(filename:join([RootDir, "releases", RelFile]))
```

But then the function only works with the current release and `RelDir` is unused.

**Comment by bitwalker** [comment]
I've pushed a fix for this and a new release (containing a bunch of other fixes and changes). 

I also discovered that it's actually not possible to use hot upgrades with `include_erts: false`, since `release_handler` checks the presence of libraries via paths contained in the `releases/RELEASES` file, and it's not possible to pre/post process that file, as the state is generated and stored in the `release_handler` process. I did quite a bit of experimenting, but it simply isn't possible :(. I believe the reason that was never supported in `release_handler` is because it has to handle upgrading ERTS libs and the runtime itself, and it has to be able to find those paths in a deterministic way. Short of rewriting `release_handler`, I don't think there is anything which can be done about it.

I don't know that it affects you, but just FYI. You need to include ERTS in order for hot upgrades to work.

**Comment by szlend** [comment]
Awesome! I'm not affected cause I always include ERTS, but it's good to know nonetheless :)
